### PR TITLE
Add Reverend's themes - also - Okay in campaign properties edit updates token properties

### PR DESCRIPTION
**Pull request by bubblobill**
### Description of the Change\
Add new theme(s) with various font sizes for visually impaired

Okay button in Campaign Properties dialog does "Update" of token properties.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RPTools/maptool/3834)

### CODE REVIEW

**Review by cwisniew — APPROVED** [review]

**Comment by Phergus** [comment]
For future reference, do not mix fixes for unrelated issues under a single PR.  Create a separate branch on your end for each and then submit as separate PRs.

You need to identify all issues that are related to this PR and make sure you have assigned them to yourself.

**Comment by bubblobill** [comment]
Addresses #3836
Adds theme and variations that is friendlier on the eyes and has different default font sizes

**Comment by bubblobill** [comment]
Because I am bad - also includes fix for #2405
Clicking okay in campaign properties now runs update() on token properties panel first.

**Review by Phergus — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RPTools/maptool/3834#-:-NOQ9Z1k4Qo0I2QESOKw:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @bubblobill)

**Pull request merged**
