### PR TITLE
Fix NPEs in protobuf conversion

### PR DESCRIPTION
**Pull request by thelsing**
### Identify the Bug or Feature request
related to #3254

### Description of the Change

fixes NPEs. Tested Messages:
Heartbeat
SetCampain
PlayerConnected

Maybe we should rename the 1.13 branch to protobuf and squash-merge it into develop before 1.13. I guess there will be more fixes.

---
This change is [Reviewable](https://reviewable.io/reviews/rptools/maptool/3288)

### CODE REVIEW

**Comment by cwisniew** [comment]
@thelsing there are a few
```java
if (blah) do_something();
```
Can you please update to meet the coding standard
```java
if (blah) {
   do_something();
}
```
I wish spotless google java plugin would enforce that rule but even though that is one of the rules for that format it doesnt enforce/reformat it.

Just makes things easier to read if everyone is doing the same thing.

We can merge this branch with develop after 1.12 which will probably be early to mid Jan (as protobuf stuff probably wont be tested enough  for that release)

**Comment by thelsing** [comment]
I think it't best it this PR stays open until I test all messages.

**Comment by Phergus** [comment]
Just FYI, I'm going to leave this PR open as your requested until you tell me otherwise.

**Comment by thelsing** [comment]
I tested everything I can. So I think this should be merged into the release-1.13 branch. I have no idea how to test the ExecLink or ExecFunction and the non tested add-on messages in #3254 
I would appreciate any help there.

**Review by Phergus — APPROVED** [review]
:lgtm:

> Reviewed 5 of 9 files at r1, 8 of 12 files at r2, 3 of 7 files at r3, 13 of 13 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/rptools/maptool/3288#-:-MtTbBXW7TLKDRmA3cjj:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @thelsing)

**Comment by Phergus** [comment]
>  I have no idea how to test the ExecLink or ExecFunction and the non tested add-on messages in #3254

Not really functionality I've ever used but I'll see if I can throw something together for some basic testing.

**Pull request merged**
