### PR TITLE
Fix compile error

### PR DESCRIPTION
**Pull request by Merudo**
- Fix compiler error due to PopupPanel.i returning a boolean

---
This change is [Reviewable](https://reviewable.io/reviews/rptools/maptool/1027)

### CODE REVIEW

**Comment by Phergus** [comment]
Travis is grabbing the wrong Java version.  This had to be fixed on the MapTool repo recently but I don't know what @JamzTheMan did to fix it.

**Comment by JamzTheMan** [comment]
This branch is stale. It needs develop merged into it.

I honestly forget why we have this branch still, I think there was a Mac issue?

@Azhrei  do you remember?

**Comment by Phergus** [comment]
A Mac issue does sound familiar.

**Comment by Phergus** [comment]
Added Issue #1029 for tracking of JIDE updates.

**Comment by Azhrei** [comment]
I've checked my email logs and places where I would normally stash notes and I don't see anything.  I don't think there was a particular macOS issue, other than I was struggling to get my Gradle builds working and I likely just got frustrated and gave up and this was the project at the time, so...? 🤷‍♂️

**Comment by Phergus** [comment]
@JamzTheMan   Okay. I opened a PR to merge develop into jide.

**Pull request merged**
