### PR TITLE
Junit tests for Json function

### PR DESCRIPTION
**Pull request by bobifle**
far from being enough, but it's still better than nothing.

issue #670

---
This change is [Reviewable](https://reviewable.io/reviews/rptools/maptool/741)

### CODE REVIEW

**Comment by Phergus** [comment]
AppVeyor says it couldn't merge the code.  Is your branch current with develop?

**Comment by JamzTheMan** [comment]
I'm not seeing what it's complaining about. It will have to wait until I'm in front of my desktop and not phone. Probably tomorrow. I wonder if tests are still turned off or something (at one point we couldn't run test suite because it blew up)

Does it dislike this PR because it's only test cases? Odd indeed...

**Comment by bobifle** [comment]
Heres' what I did:

git fetch upstream
git checkout develop
git merge upstream/develop
git push
git checkout json
git merge develop
git push

all where fast forwards without conflicts...

copy paste of my git log on my json branch:

`*   c7507d3 (HEAD -> json, origin/json) Merge branch 'develop' into json
|\
| * 68706c6 (upstream/develop, origin/develop, develop) Changed getInfo("server") macro to use ServerPolicy.toJSON directly (#738)
* | 3fd5f33 spotless on json tests
* | e5731ee use a resource fiel for json rather that constructed within the test code
* |   f646ac6 Merge branch 'develop' into json
`

Sorry I'm very new to this, I don't know if this is useful info

**Comment by JamzTheMan** [comment]
Yea I don't think it's anything you did. In fact there were successful builds in Travis and Appveyor so who knows what happened.

I think I will just target a temp branch, merge it, if that all goes well then just merge it back into develope.

**Pull request merged**
