### PR TITLE
update parser to 1.8.2, dicelib to 1.6.5

### PR DESCRIPTION
**Pull request by nmeier**
#1898

---
This change is [Reviewable](https://reviewable.io/reviews/rptools/maptool/2098)

### CODE REVIEW

**Comment by nmeier** [comment]
Something wrong with dicelib 1.6.5 release package

https://jitpack.io/com/github/RPTools/dicelib/1.6.5
Build failed. See the log at jitpack.io

**Comment by Phergus** [comment]
Not sure what it was complaining about but I did realize the dicelib had a dependency on parser.  The build.gradle for dicelib has been updated to reference parser 1.8.2 and a new release 1.6.6 was made for dicelib.  Update your change for that.

BTW, why did you make this a separate PR instead of adding it to #2086 ?

**Comment by nmeier** [comment]
oops, got confused between PRs it seems, should have added to other yes

**Comment by nmeier** [comment]
Do you want me to consolidate the change to dicelib 1.6.6 into #2086 ?

**Comment by Phergus** [comment]
That simplifies things as then all the parts that need each other get done at once.

**Pull request closed without merging**
