### PR TITLE
Move cleanup of overlays and javascript context to campaign manager

### LINKED ISSUE #3457: [Bug]:  Cleanup for JavaScript contexts and Overlays is occurring in the wrong place loading a new campaign
### Describe the Bug

The clearing of interfaces and overlays from an old campaign occurs AFTER loading a new campaign.
This results in the clearing out of newly created JavaScript contexts for the add-ons in the new campaign causing their JavaScript functions to fail and allowing JavaScript on overlays to keep running once the campaign had completed, which could lead to errors or updating of tokens in the new campaign.

### To Reproduce

1. Create a campaign with an add-on that uses JavaScript
2. Save campaign
3. Create a new campaign
4. Then load the first campaign, the JavaScript in the add-on will not function correctly as there context has been removed.

### Expected Behaviour

Resetting of overlays and JavaScript contexts should happen before the new campaign is set.

### Screenshots

_No response_

### MapTool Info

Version 1.11.x

### Desktop

All

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by cwisniew**
### Identify the Bug or Feature request
resolves #3457
@perkinslr are you able to verify this fixes the behaviour you were experiencing?

### Description of the Change
Moved the clean up code for overlays and javascript contexts to the clearCampaignData() method in the campaign manager so it will be called at the correct time.

### Possible Drawbacks
I don't think there will be any, and from my quick tests I was not able to trigger any problems.

### Release Notes
- Fix for overlays being cleared at wrong time on campaign load
- Fix for JavaScript contexts being cleared at wrong time on campaign load.

---
This change is [Reviewable](https://reviewable.io/reviews/rptools/maptool/3458)

### CODE REVIEW

**Comment by perkinslr** [comment]
No, this doesn't appear to resolve it.  Now not only do the js contexts get cleared, the addon library itself appears to be getting cleared...

**Review by Phergus — APPROVED** [review]
:lgtm:

> Reviewed 1 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/rptools/maptool/3458#-:-N6Oh0Ws65LaxTeW9frw:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @cwisniew)

**Review by perkinslr — APPROVED** [review]

**Review by cwisniew — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/rptools/maptool/3458#-:-N6PxVBT-K809O3y4hg1:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @perkinslr)

___
*[`src/main/java/net/rptools/maptool/client/MapTool.java` line 972 at r1](https://reviewable.io/reviews/rptools/maptool/3458#-N67UxmLnxNWrwpNsi1b-r1-972:-N6PxXJ6-fJNmsCTT15J:b-896fix) ([raw file](https://github.com/rptools/maptool/blob/cf82a010e95ccbc4fde9e3dfdfefd5a6b595bf10/src/main/java/net/rptools/maptool/client/MapTool.java#L972)):*
<details><summary><i>Previously, perkinslr (Logan Perkins) wrote…</i></summary><blockquote>

Removing this resolves the javascript contexts resetting.
Since the addon cleanup code runs elsewhere, the javascript contexts still properly get reset when switching campaigns.
</blockquote></details>

Done.

**Review by Phergus — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/rptools/maptool/3458)* status: all files reviewed, 1 unresolved discussion (waiting on @perkinslr)

**Comment by Phergus** [comment]
Still has a pending discussion issue...

**Comment by perkinslr** [comment]
I still don't see a way to mark the conversation resolved.  I just deleted the original comment, doesn't look like that did anything.  I might not be able to mark it resolved, since I'm not in the org.  In projects where I *am* a member, anyone with sufficient permissions can mark a discussion resolved.  

I don't know what else to do here, beyond you guys either disabling the check or starting a new PR for it.

**Review by perkinslr — COMMENTED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/rptools/maptool/3458)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @cwisniew)

**Review by Phergus — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/rptools/maptool/3458)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @cwisniew)

**Pull request merged**
