### PR TITLE
Included possible change to map loading as highlighted in #2656.

### PR DESCRIPTION
**Pull request by michaelperino**
It's a little gross but reimplements expected behavior.

Implemented changes:
*Tracks GUID when a ZoneRenderer is removed. If a map exists with that GUID when the next ZoneRenderer is added, switches to that map.

I might have my Tuesday group use this branch for our game to see if I can get any weird errors to pop up. At one point Malwarebytes got mad at me with my two client test setup, but I couldn't reproduce that. LMK if I need to make any edits to conform to contributor rules.

---
This change is [Reviewable](https://reviewable.io/reviews/rptools/maptool/2659)

### CODE REVIEW

**Comment by Phergus** [comment]
Okay but what about this scenario:

- Two players: P1 & P2.  Two maps: M1 & M2
- P1 is looking at M1.  GM makes change to M1 and P1 gets the momentary disruption but stays on the M1.
- P2 is viewing M2 which has campaign lore/history.  With what you're proposing when the GM changes M1, P2 is forced to the updated M1.

**Comment by michaelperino** [comment]
>     * P2 is viewing M2 which has campaign lore/history.  
>     With what you're proposing when the GM changes M1, P2 is forced to the updated M1.

That's not quite how it works. The change is made on the client side addition or removal of zones. It doesn't change how the server distributes the changes. If P2 is on a different map (even if P1 is on changed map) it won't force P2 to changed map according to my testing. Here's a real fast video showing current behavior in a derivative branch I was using for the display name test.

https://user-images.githubusercontent.com/33206261/118750263-b500e400-b824-11eb-81c2-5513c82e3444.mp4

**Comment by Phergus** [comment]
Didn't say anything about the server and was just going by what you said:

> Tracks GUID when a ZoneRenderer is removed. **If a map exists with that GUID when the next ZoneRenderer is added, switches to that map.**

But what you did is different.

**Review by Phergus — APPROVED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/rptools/maptool/2659)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @michaelperino)

**Pull request merged**
