### PR TITLE
Macro editor help

### PR DESCRIPTION
**Pull request by Azhrei**
This change is [Reviewable](https://reviewable.io/reviews/rptools/maptool/274)

### CODE REVIEW

**Comment by JamzTheMan** [comment]
___
*[doc/How_To_Setup_Eclipse.md, line 28 at r1](https://reviewable.io/reviews/rptools/maptool/274#-L_AIt7j1U5mhtp7RMWu:-L_AIt7j1U5mhtp7RMWv:bp71w54) ([raw file](https://github.com/rptools/maptool/blob/11496dee34d142ccb442a4c718aaa255af5b198c/doc/How_To_Setup_Eclipse.md#L28)):*
> ```Markdown
>     location would usually be `C:\Program Files\eclipse`. (If you simply extract the zip file, it will
>     create the top level `eclipse` directory.) Create a shortcut for Eclipse and paste it onto your
>     desktop, if desired.   
> ```

FYI: Eclipse for windows is normal win64 exe install now if you follow the normal download links/google search.

**Comment by JamzTheMan** [comment]
___
*[doc/How_To_Setup_Eclipse.md, line 57 at r1](https://reviewable.io/reviews/rptools/maptool/274#-L_AKL_78Rp5F_Q1zww7:-L_AKL_8AF85vc_IlUG8:bqk2886) ([raw file](https://github.com/rptools/maptool/blob/11496dee34d142ccb442a4c718aaa255af5b198c/doc/How_To_Setup_Eclipse.md#L57)):*
> ```Markdown
>         C:\Program Files\Java\jdk1.8.0_40\bin\javaw.exe
>         ```
> 7.  You can now start Eclipse and it will use the Java program you specified.
> ```

Somewhere we need to tell them to run 'gradlew eclipse' to finish Eclipse configuration, after Git/Gradle steps?

**Comment by JamzTheMan** [comment]
___
*[doc/How_To_Setup_Eclipse.md, line 170 at r1](https://reviewable.io/reviews/rptools/maptool/274#-L_AKbPz7zFB4_xqCzJ8:-L_AKbPz7zFB4_xqCzJ9:b-7m5fj7) ([raw file](https://github.com/rptools/maptool/blob/11496dee34d142ccb442a4c718aaa255af5b198c/doc/How_To_Setup_Eclipse.md#L170)):*
> ```Markdown
> 7. Click **Run**, this should now launch Maptool!
> 
> If you got through all that, congratulations!
> ```

Would it be worth noting here (or maybe at the very top?) that a a bare minimum, if they have "Git" installed, 2-3 steps on any OS can get MapTool and run it? useful to run dev builds/pre-release?

git clone https://github.com/RPTools/maptool.git
git checkout <branch name>
gradlew run

**Comment by JamzTheMan** [comment]
___
*[doc/How_To_Setup_UI_Tools.md, line 29 at r1](https://reviewable.io/reviews/rptools/maptool/274#-L_ALTH17sihEXsGS8lU:-L_ALTH17sihEXsGS8lV:b-p7hvnc) ([raw file](https://github.com/rptools/maptool/blob/11496dee34d142ccb442a4c718aaa255af5b198c/doc/How_To_Setup_UI_Tools.md#L29)):*
> ```Markdown
> ----------------------------
> 
> The JavaFX Scene Builder application has been handed over to the open source community and as a consequence it can be hard to find the Scene Builder install. The latest version as of this writing is SceneBuilder 10.0.0 and is available from [GluonHQ.com](https://gluonhq.com/products/scene-builder/)
> ```

FYI 11 is now out as a Release Candidate and probably should be used for FX branch as we're using Java 11

**Comment by JamzTheMan** [comment]
___
*[src/main/java/net/rptools/maptool/client/functions/HTTP_Functions.java, line 45 at r1](https://reviewable.io/reviews/rptools/maptool/274#-L_AM0fgCPsgrCA_hcRS:-L_AM0fgCPsgrCA_hcRT:b-y22i7s) ([raw file](https://github.com/rptools/maptool/blob/11496dee34d142ccb442a4c718aaa255af5b198c/src/main/java/net/rptools/maptool/client/functions/HTTP_Functions.java#L45)):*
> ```Java
>  * <p>getRequest(URL) :: Takes a URL as a string and sends a GET request, returning HTTP data.
>  * postRequest(URL, Parameters) :: Takes a URL as a string, and a JSON array of parameters, and
>  * sends a POST request, returning HTTP data. >>>>>>> merge-from-nerps
> ```

I'll clean all this up when I get the RESTful stuff a clean up pass here soon

**Comment by JamzTheMan** [comment]
___
*[src/main/java/net/rptools/maptool/client/functions/ZoomFunctions.java, line 103 at r1](https://reviewable.io/reviews/rptools/maptool/274#-L_AMJca3AvfMIi1yjqK:-L_AMJca3AvfMIi1yjqL:broqkcy) ([raw file](https://github.com/rptools/maptool/blob/11496dee34d142ccb442a4c718aaa255af5b198c/src/main/java/net/rptools/maptool/client/functions/ZoomFunctions.java#L103)):*
> ```Java
>    *     current view.
>    * @param arg should be boolean (pixels=true, cells=false)
>    * @return String of coordinates (will work as JSON array) >>>>>>> merge-from-nerps
> ```

Merge conflicts here...

**Comment by JamzTheMan** [comment]
___
*[src/main/java/net/rptools/maptool/client/ui/zone/vbl/TokenVBL.java, line 33 at r1](https://reviewable.io/reviews/rptools/maptool/274#-L_AMrKP943ems1o0bvO:-L_AMrKP943ems1o0bvP:b9geimn) ([raw file](https://github.com/rptools/maptool/blob/11496dee34d142ccb442a4c718aaa255af5b198c/src/main/java/net/rptools/maptool/client/ui/zone/vbl/TokenVBL.java#L33)):*
> ```Java
>  * <<<<<<< HEAD A utility class that creates and returns and Area based on image pixels ======= A
>  * utility class that creates and returns and Area based on image pixels A few convience methods to
>  * handle other Token VBL functions >>>>>>> merge-from-nerps
> ```

another merge conflict. just docs but worth noting...

**Comment by JamzTheMan** [comment]
Reviewable does make looking and commenting on the diffs nicer!

Everything looked good. Nothing but minor doc notes here and there.

**Comment by Azhrei** [comment]
Thanks.  I'll get the merge conflict artifacts removed and then merge.  I revised two or three of the markdown docs and then realized that they all needed a fresh review, so I'll get to that next.

**Comment by Azhrei** [comment]
And I don't see any way to change the way line comments are wrapped (well, without figuring out and modifying the plugin itself).  We either change the way we do line comments, or switch back to a configurable approach.  (I don't usually put line comments on the ends of exist code lines, so not a big deal for me personally either way.)

**Comment by Azhrei** [comment]
Hm, lots of comments to reply to, but each one is a separate post.  Kind of a pain to wrap them all up here...

> FYI: Eclipse for windows is normal win64 exe install now if you follow the normal download links/google search.
But there's no way to select whether you get EE or regular, based on what the download page says.  My bet is that the install process asks that question, but then I'm explaining the same steps anyway since macOS downloads a **.dmg** file and Linux downloads a **.tar.gz*.  Might as well just stick with the explicit choices.

> Somewhere we need to tell them to run 'gradlew eclipse' to finish Eclipse configuration, after Git/Gradle steps?
Yes, I see now that the taels are wrong.  The **Build MapTool with Gradle** is actually building it with gradle from within Eclipse.  I'll redo that to make it more clear.

> Would it be worth noting here (or maybe at the very top?) that a a bare minimum, if they have "Git" installed, 2-3 steps on any OS can get MapTool and run it? useful to run dev builds/pre-release?
I can add a **TL; DR** section for those who are experienced with Eclipse and/or Gradle already.

I'll cover the UI tools in a separate post.

**Comment by Azhrei** [comment]
Concerning the UI setup doc:

> FYI 11 is now out as a Release Candidate and probably should be used for FX branch as we're using Java 11
It's not shown on the main download page, so I'll stick with 10 for now.

> I'll clean all this up when I get the RESTful stuff a clean up pass here soon

Okay, but there's a merge conflict artifact that didn't get cleaned up.  I'll get that one, and another elsewhere.  I think I must've hit **Save** in Eclipse and it reformatted everything, causing the conflict markers to be embedded.  I'll need to be careful about that in the future.  Thanks.

**Comment by JamzTheMan** [comment]
I figured you could read/comment through reviewable? Sorry if it was all scattered, that's how that tool does it.

All in all nothing major.

**Comment by Azhrei** [comment]
Yep, all of the merge artifacts are embedded in JavaDoc.  Easy to fix.  (And I should've looked to see if I could reply directly in the Reviewable screen as well.  I'll do that for the next one.)

**Comment by JamzTheMan** [comment]
___
*[doc/How_To_Setup_Eclipse.md, line 57 at r1](https://reviewable.io/reviews/rptools/maptool/274#-L_AKL_78Rp5F_Q1zww7:-L_KksdKCbtG1k-iZ9_e:b-hxjyw2) ([raw file](https://github.com/rptools/maptool/blob/11496dee34d142ccb442a4c718aaa255af5b198c/doc/How_To_Setup_Eclipse.md#L57)):*
<details><summary><i>Previously, Azhrei (Frank Edwards) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Awesome

**Comment by JamzTheMan** [comment]
:lgtm:

**Pull request merged**
