### PR TITLE
Feature: Issue #185 - Sorting artpacks

### PR DESCRIPTION
**Pull request by LukasDJacobs**
This addresses issue #185 
To accomplish sorting by author as well as by name, a new format for the listArtPacks file on the server is required. I recommend just using a second file, next to the "old" format and changing the `private static final String LIBRARY_LIST_URL` variable in `net.rptools.maptool.client.ui.AddResourceDialog` to point to the new index file. A gist, containing the new index file format can be found [here](https://gist.github.com/Mornielome/7fc77a142ee3e207fa48dbfa33cf2c8d)

Regarding a lot of the "changed" code that looks exactly the same: There seem to have been a lot of mixed tabs and spaces for indentation in the file. I settled with tabs, but if this is wrong I can easily change this to be spaces.

---
This change is [Reviewable](https://reviewable.io/reviews/rptools/maptool/199)

### CODE REVIEW

**Comment by Mornielome** [comment]
```
Resolving edelivery.oracle.com (edelivery.oracle.com)... 23.79.9.175
Connecting to edelivery.oracle.com (edelivery.oracle.com)|23.79.9.175|:443... connected.
HTTP request sent, awaiting response... 302 Moved Temporarily
Location: http://download.oracle.com/otn-pub/java/jdk/9.0.4+11/c2514751926b4512b076cc82f959763f/jdk-9.0.4_osx-x64_bin.dmg?AuthParam=1533485084_33a8a49fe271b938a2dde8cfdae7807b [following]
--2018-08-05 16:02:44--  http://download.oracle.com/otn-pub/java/jdk/9.0.4+11/c2514751926b4512b076cc82f959763f/jdk-9.0.4_osx-x64_bin.dmg?AuthParam=1533485084_33a8a49fe271b938a2dde8cfdae7807b
Connecting to download.oracle.com (download.oracle.com)|23.46.56.164|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2018-08-05 16:02:45 ERROR 404: Not Found.
```

There seems to be a problem with the CI system (or with oracles servers...)

Regarding the other error: I seem to have made an error regarding formatting or something like that (spotless check fails) - my bad. Will look into it and fix it.

**Comment by Mornielome** [comment]
Still a problem with CI system or oracle servers for the macOS build. The other test passes.

**Comment by Azhrei** [comment]
There's support to be an Eclipse export of preferences settings to handle formatting, but the last time I checked it, it didn't seem to work properly.  It'll import, but the changes don't see to be applied.  Not helpful if you're not using Eclipse, either.  But running spotless on it should keep it in sync with the existing code base.

Ignore the macOS build for now.  If it builds on Linux, then it's fine.  I have some time this month and plan to work on the build configuration.

**Comment by Mornielome** [comment]
I am actually developing using IntelliJ - works fine. Found out that I could just import the eclipse formatting file into it and reformat. It builds fine on Linux and spotless doesn't complain. That's what the latest commit is

**Comment by JamzTheMan** [comment]
@LukasDJacobs Thanks for the submission!  I'm trying to build the next dev release based off this branch.  Could you fix the conflicts and build against the merge-from-nerps branch?  I can get it into a future Developer Release after the issues are resolved.

**Comment by LukasDJacobs** [comment]
I can have a quick go at it tomorrow, but I do not have time to fiddle a lot with it. If it's a bit more involved it could be next week until I can do it

**Comment by JamzTheMan** [comment]
No hurry, i probably won't do a release for another 2 weeks.

**Pull request closed without merging**
