### PR TITLE
Add mapName and localization to MacroFunctions

### LINKED ISSUE #1072: Add "mapName" parameter and localization to MacroFunctions
**Is your feature request related to a problem? Please describe.**
Meta macro functions such as `getMacroProps` and `getMacroIndexes` do not have a "mapName" argument.

Additionally, the error messages of the meta macro functions are not localized.

**Describe the solution you'd like**
Add a mapName macro argument to the functions, and add localization to the error messages.

### PR DESCRIPTION
**Pull request by Merudo**
- Add parameter "mapName" to MacroFunctions
- Add localization to MacroFunctions error message
- Fix applyToSelected ignored by createMacro
- Close #1072,  #1075

---
This change is [Reviewable](https://reviewable.io/reviews/rptools/maptool/1076)

### CODE REVIEW

**Comment by cwisniew** [comment]
This fix will have to wait until the JSON updates have been applied as its likely to cause conflicts.

**Comment by Phergus** [comment]
# HOLD UNTIL JSON UPDATE IS FINISHED

**Comment by Merudo** [comment]
I thought I left the lines dealing with json untouched, but better be safe than sorry.

**Comment by Phergus** [comment]
Re-opening now that JSON merge is complete.

**Comment by Phergus** [comment]
@Merudo - Would you like to update MacroFunctions and re-commit?

**Comment by Merudo** [comment]
@Phergus I've updated the commit.

**Comment by cwisniew** [comment]
@Merudo looks good, but could you make the methods non static please.
In the non to distant future the plan is it add dependency injectection with something like google guice and require new stuff to use dependency injection / convert old stuff where its not too hard and make sense or as its refactored. 

This will allow for less tight coupling, cleaner code, easier unit tests. I know its a huge hill to climb to get there and we may never achieve it completely but I also prefer if we dont keep adding to the hill :)

**Comment by Merudo** [comment]
@cwisniew sure thing. I was wondering were we stood regarding the "should static function be avoided" debate.

**Pull request merged**
