### PR TITLE
Remove putTokens in macro functions

### LINKED ISSUE #761: Bar macro functions seem to be using putToken() and appear to cause the "full token copy" problem when two or more people try to modify a token via macros.
**Describe the bug**
MapTool 1.5.4 bar macro functions seem to be using putToken() and appear to cause the "full token copy" problem when two or more people try to modify a token via macros.

**To Reproduce**
1. Create macro A that calls **setBarVisible("Health", 1)** and **setBar("Health", 5/10)** for a token, receives input, and sets token property a.
2. Create macro B that receives input and sets token property b.
3. Start macro A with token X selected but let it wait for input.
4. Start macro B with token X selected and provide input so that it sets token property b and exits.
5. For macro A, provide input so that it sets property a and exits.
6. Property b is not set.

**Expected behavior**
In step #6, property b should be set.

**Screenshots**

**MapTool Info**
- Version: 1.5.4

**Desktop (please complete the following information):**
 Windows 10

**Additional context**
The state macro functions appear to be working.  Don't seem to cause this issue.

### PR DESCRIPTION
**Pull request by Merudo**
- Change so that many token functions now only update the relevant information instead of sending the whole token
- Close #761
- Functions affected: addToInitiative, setInitiative, setInitiativeHold, setBar, setBarVisible, setName, setGMName, setHalo, setTokenOpacity, setTokenImage, setTokenPortrait, getTokenHandout, setLabel, resetProperty, setTerrainModifier, setVisible, setOwnerOnlyVisible, setAlwaysVisible, setTokenVBL

---
This change is [Reviewable](https://reviewable.io/reviews/rptools/maptool/764)

### CODE REVIEW

**Comment by rkathey** [comment]
There’s a setCharsheetImage?

**Comment by Phergus** [comment]
If I'm not mistaken, that's the handout image.

**Comment by Merudo** [comment]
I used the wrong name my bad.

**Comment by Phergus** [comment]
- [ ] addToInitiative
- [ ] setInitiative
- [ ] setInitiativeHold
- [ ] setBar
- [ ] setBarVisible
- [ ] setName
- [ ] setGMName
- [ ] setHalo
- [ ] setTokenOpacity
- [ ] setTokenImage
- [ ] setTokenPortrait
- [ ] getTokenHandout
- [ ] setLabel
- [ ] resetProperty
- [ ] setTerrainModifier
- [ ] setVisible
- [ ] setOwnerOnlyVisible
- [ ] setAlwaysVisible
- [ ] setTokenVBL

**Pull request merged**
