### PR TITLE
Adds missing variables init.current and init.hold

### LINKED ISSUE #753: Add missing reserved variable names to editor syntax
**Is your feature request related to a problem? Please describe.**
`init.current` and `init.round` reserved variables are not highlighted in macro editor

**Describe the solution you'd like**
They should be highlighted.

**Additional context**
Also not documented on Wiki.

### PR DESCRIPTION
**Pull request by xdy**
This should fix #753 .
I didn't add them to the datatypes tag in MapToolScript.xml where they are also missing. Should I have done that?

---
This change is [Reviewable](https://reviewable.io/reviews/rptools/maptool/981)

### CODE REVIEW

**Comment by Phergus** [comment]
Make a comment on issue #753 so that I can assign it to you.

**Comment by Phergus** [comment]
Held pending 1.5.8 release.  Will be part of 1.5.9.

**Comment by JamzTheMan** [comment]
@Phergus these probably need a little magic to get them to show in the macro editor...

**Comment by Phergus** [comment]
Roger that.  I'll check it and advise.

**Comment by Phergus** [comment]
@JamzTheMan  Adding them to `MapToolScriptSyntax appears to be all that's needed to get them recognized by the editor.  What's missing of course is any kind of description as is missing for the others.

@xdy  As far as I know the MapToolScript.xml file isn't used.

**Comment by JamzTheMan** [comment]
cool ya, sounds about right, been awhile since I did that code...

**Pull request merged**
