### PR TITLE
New Crowdin updates

### PR DESCRIPTION
**Pull request by bubblobill**
This change is [Reviewable](https://reviewable.io/reviews/RPTools/maptool/4724)

### CODE REVIEW

**Review by cwisniew — APPROVED** [review]

**Comment by cwisniew** [comment]
@bubblobill 
The build is failing because it can't find the following
CampaignPropertiesDialog.button.import.tooltip

**Comment by bubblobill** [comment]
Doesn't look like something I would have done on purpose. Will investigate.

**Comment by cwisniew** [comment]
Might have been caused by fixing the merge conflicts :(

**Comment by bubblobill** [comment]
It was definitely part of this branch - bubblobill/maptool/UI_Text_Campaign_Properties
image

Can we pull it again?

**Comment by bubblobill** [comment]
Okay. Just updated my branch and it has disappeared. le sigh

**Comment by bubblobill** [comment]
@cwisniew 
This is the culprit. Undo this and it should fly.

_Merge pull request #4723 from bubblobill/UI_Text
UI text - added Cover VBL tooltip_

**Comment by bubblobill** [comment]
It's old and failing tests so I'm just going to kill it. Maybe I'll do it all again later.

**Pull request closed without merging**
