### PR TITLE
Fixes incorrect ordering of CSS when the CSS is loaded from a macro button (eg CSS@lib:css)

### LINKED ISSUE #1853: Frame5/Dialog5/Overlay load CSS in incorrect order when link points to  macro
**Describe the bug**
When CSS is loaded from a macro via the link tag it is inserted at the top of the head element before anything else.

**To Reproduce**
Campaign Attached which demonstrates the error.

**Expected behavior**
CSS should be loaded in the order it is defined in the link tag.

**MapTool Info**
1.7 Alpha
[CSSPrecedenceError.zip](https://github.com/RPTools/maptool/files/4637990/CSSPrecedenceError.zip)

### PR DESCRIPTION
**Pull request by cwisniew**
Does what it says on the tin
closes #1853

---
This change is [Reviewable](https://reviewable.io/reviews/rptools/maptool/1854)

### CODE REVIEW

**Comment by cwisniew** [comment]
#1853 contains attached campaign demonstrating the error

**Comment by Merudo** [comment]
Won't this cause issues if more than one link is added to the page?

**Comment by Merudo** [comment]
Nice! Cleaner logic too than what was there before.

Two things:

1) Parameter `refNode` is now useless and should be removed
2) `System.out.println(html);` prints the whole document to the console. I assume this was for testing, but it should be removed

**Comment by cwisniew** [comment]
yeah I need to remove that output oops!
But just noticed there is a bug still when there are multiple CSS from macro they are in reverse order.

**Comment by cwisniew** [comment]
pushed fix for reverse ordering of ccs@lib:token
also addressed above feedback.

**Pull request merged**
