### PR TITLE
Catch abort

### PR DESCRIPTION
**Pull request by oliver-szymanski**
Ensure catchAbort for UDF, straight macros and roll options Issue #287 

Previous catchAbort ignored direct macro calls and had an issue with
some roll options. This fixes that.

Sample of calls (with raiseAbort@this being a macro doing an abort(0)
and raiseAbort, raiseAbortNotIgnoreOutput 2 UDFs pointing to the macro
wit/without output ignored):

`[h: var = 0]
[h: macro.catchAbort = 1]
[h: result = "default value"]

abort_r: [r: result = abort(var)]
<br>result_r: [r: result]<br>

abort_t: [t: result = abort(var)]
<br>result_t: [r: result]<br>

abort_t_code: [t, code: {
	[result = abort(var)]
}]
<br>result_t_code: [r: result]<br>

abort_r_code: [r, code: {
	[result = abort(var)]
}]
<br>result_r_code: [r: result]<br>

abort_f: [raiseAbort()]
<br>result_f: [r: result]<br>

abort_f_with_output: [raiseAbortNotIgnoreOutput()]
<br>result_f_with_output: [r: result]<br>

abort_macro: [macro("raiseAbort@this"): ""]
<br>result_macro_code: [r: result]<br>

More text...`

---
This change is [Reviewable](https://reviewable.io/reviews/rptools/maptool/293)

### CODE REVIEW

**Comment by Azhrei** [comment]
I'm thinking it would be best to keep this in the same PR as the original code.  That way if it has to be reverted before 1.5.0 final is released, it's a single button click on "revert" in that PR.  I don't know how @JamzTheMan feels about it, though, and he's planning to do the release...

**Comment by oliver-szymanski** [comment]
Something went wrong anyway, this looks suspicious " 
Merge branch 'jadebringer' into catchAbort "

**Comment by Azhrei** [comment]
And we definitely don't want the `addFramework` code for the 150 release.  That _must_ be a separate PR and it likely won't be merged any time soon as it's not something we want to tackle at this point.

**Comment by oliver-szymanski** [comment]
Yeah, as said above something is wrong with that merge from another branch. I try with the original PR

**Pull request closed without merging**
