### PR TITLE
First go at a BUG report template as mentioned in #338

### PR DESCRIPTION
**Pull request by Tdue21**
This change is [Reviewable](https://reviewable.io/reviews/rptools/maptool/342)

### CODE REVIEW

**Comment by JamzTheMan** [comment]
Did you look in develope branch?

**Comment by Tdue21** [comment]
Yeah, but not until after I had submitted the PR at commented on the issue, and saw your comment.

**Comment by Phergus** [comment]
The template from the Nerps fork was added to repo so this is no longer needed?

**Comment by JamzTheMan** [comment]
Closed as basically a duplicate now and merge conflicts. Submit another PR if changes to the now existing one is requested.

**Pull request closed without merging**
