### PR TITLE
Updated SwingWorker from Java 5 API

### PR DESCRIPTION
**Pull request by mikehenry-se**
Since Bintray and JCenter has been sunsetted and closed down by JFrog this past week,, old JARs for SwingWorker from Java 5 no longer seem available. Since Java 6 SwingWorker has been part of the JRE and no need for external JAR dependencies should be necessary.

Also, a minor gradle update is included, removing support for Windows 9x.

_Sketchy_

---
This change is [Reviewable](https://reviewable.io/reviews/rptools/maptool/2737)

### CODE REVIEW

**Comment by Phergus** [comment]
Thanks jumping in as a contributor to MapTool.  Couple minor issues.

Normally we need an issue opened proposing the changes in case discussion is needed first. 

You mentioned on Discord that builds were failing.  Given that we just released beta-3 on all platforms the builds obviously weren't failing for the CI process or on dev's machines.  Can you elaborate?

You've included a new `gradle-wrapper.jar` file but without a corresponding update to the `gradle-wrapper.properties` file. Also need a comment about why it was updated.

**Comment by mikehenry-se** [comment]
Thank you, Phergus. I appreciate the structure and quality you bring to the project. I will work to follow the procedures you use and contribute if and where I can.
I think JFrog took JCenter offline just last week, which may have been after you built the beta 3 binary. Checking out the current `develop` and building it locally failed for me, hence the update. If you have the SwingWorker JAR-file cached then builds may be repeatable, YMMV.
I guess the gradle changes aren't entirely necessary and I would be happy to clean them up or revert them. I noticed during my build that there were deprecated features used that would hinder future upgrades. Let me know how you would like to proceed.

**Comment by Phergus** [comment]
Thanks Mike.  Didn't find the swingworker.jar in my gradle cache but maybe I missed it.  As you said though it isn't needed any more so cleaning up the `build.gradle` file and those source files looking for it is a good thing.

If the changes made to clean up the jcenter and swingworker usage don't require the change to the `gradle-wrapper.jar` then i would rather see gradle updated in a separate PR.  We are getting a number of gradle warnings now with builds that should be cleaned up sooner rather than later to move forward with gradle versions.  If you would like to pursue that let's do it in a separate issue.

**Comment by mikehenry-se** [comment]
Reverted the gradle changes, leaving only the SwingWorker cleanup.

**Comment by mikehenry-se** [comment]
Evn though it compiles, I noticed when building that with this change the right MT version is not picked up, displaying v0.0.1 instead of 1.9.0. I'll investigate and come with a fix.

**Comment by cwisniew** [comment]
> Eevn though it compiles, I noticed when running that with this change the right MT version is not being picked up, displaying v0.0.1 instead of 1.9.0. I'll investigate and come with a fix.

v 0.0.1 is the version number given to any non tag based build. This is due to the packager change required to move to JDK 14 it doesnt version numbers with dev/alpha/beta etc in them ( I think partially due to windows MSI package limitations).

**Comment by mikehenry-se** [comment]
> > Eevn though it compiles, I noticed when running that with this change the right MT version is not being picked up, displaying v0.0.1 instead of 1.9.0. I'll investigate and come with a fix.
> 
> v 0.0.1 is the version number given to any non tag based build. This is due to the packager change required to move to JDK 14 it doesnt version numbers with dev/alpha/beta etc in them ( I think partially due to windows MSI package limitations).

Ok, thanks! Just wanted to make sure nothing broke.

**Review by cwisniew — APPROVED** [review]
> Reviewed 5 of 8 files at r1, 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/rptools/maptool/2737)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @mikehenry-se)

**Review by Phergus — APPROVED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/rptools/maptool/2737)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @mikehenry-se)

**Review by Phergus — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/rptools/maptool/2737#-:-McZZie04848lBrtVmMH:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @mikehenry-se)

**Review by Phergus — APPROVED** [review]
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/rptools/maptool/2737)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @mikehenry-se)

**Pull request merged**
