### PR TITLE
Revert "Add unique light sources on tokens, and macros for manipulating them."

### PR DESCRIPTION
**Pull request by bubblobill**
Reverts RPTools/maptool#4356

Cannot open edit token dialog and a few other things seem a bit squirly.
Please take this back

- - -
This change is [Reviewable](https://reviewable.io/reviews/RPTools/maptool/4374)

### CODE REVIEW

**Comment by kwvanderlinde** [comment]
Which other things?

The problem with the Edit Token dialog is not due to the change you're reverting.

**Comment by kwvanderlinde** [comment]
#4375 fixes the dialog

**Comment by bubblobill** [comment]
hopefully other changes to the token will also work. Had trouble with things like setting halos.
assuming it was something to do with token data
didn't dig deep, just noticed I couldn't play with the bit I wanted

**Comment by kwvanderlinde** [comment]
For something like that it's possible you need to refresh your protobuf codegen.

**Comment by kwvanderlinde** [comment]
@bubblobill Can you confirm whether things work for you now on the latest `develop`?

**Comment by bubblobill** [comment]
Just had a quick test. The bits I was playing with previously are behaving in the current develop

**Pull request closed without merging**
