### PR TITLE
get/setMapVisible: return BigDecimal instead of String 0/1

### PR DESCRIPTION
**Pull request by aRTy42**
The functions returned a string, which caused `assert()` and similar logic checks to not work as expected (string "0" treated as true).
Changed to an explicit BigDecimal, which seems to be the most common format for this kind of situation.
I checked these for comparison:
[isVisibleFunction](https://github.com/RPTools/maptool/blob/da4c630ae0f4c344f06c23e2eead12db3bde9cfb/src/main/java/net/rptools/maptool/client/functions/isVisibleFunction.java#L85-L104)
[isDialogVisible / isFrameVisible](https://github.com/RPTools/maptool/blob/da4c630ae0f4c344f06c23e2eead12db3bde9cfb/src/main/java/net/rptools/maptool/client/functions/MacroDialogFunctions.java#L64-L74)
[isBarVisible](https://github.com/RPTools/maptool/blob/da4c630ae0f4c344f06c23e2eead12db3bde9cfb/src/main/java/net/rptools/maptool/client/functions/TokenBarFunction.java#L97-L116)
[getAlwaysVisible](https://github.com/RPTools/maptool/blob/da4c630ae0f4c344f06c23e2eead12db3bde9cfb/src/main/java/net/rptools/maptool/client/functions/TokenVisibleFunction.java#L341-L350)

Corresponding issue: #2652

---
This change is [Reviewable](https://reviewable.io/reviews/rptools/maptool/2653)

### CODE REVIEW

**Review by Phergus — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/rptools/maptool/2653#-:-M_lTw7ADVEWJr4xi6UG:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @aRTy42)

**Comment by Phergus** [comment]
@aRTy42 need to run Spotless

**Comment by aRTy42** [comment]
As in "please remember that for the future" or "reformat the PR?"

**Comment by Phergus** [comment]
As in the build verification won't pass until you do `gradlew spotlessApply`

**Comment by Phergus** [comment]
And then push the change up.

**Review by Phergus — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/rptools/maptool/2653#-:-M_lgubS16oip2IS1pVV:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @aRTy42)

**Pull request merged**
