### PR TITLE
#1045 Update all dependencies

### PR DESCRIPTION
**Pull request by xdy**
I've updated everything that isn't in another PR, or is NoiseLib (as that is built using a later java version.)
I've done a fair amount of testing, and it seems to work fine.

---
This change is [Reviewable](https://reviewable.io/reviews/rptools/maptool/1048)

### CODE REVIEW

**Comment by Phergus** [comment]
Was it Spotless that made all the changes to the various macro classes?

**Comment by xdy** [comment]
Yep, that was spotless.

**Comment by Phergus** [comment]
That wacky guy.

**Comment by xdy** [comment]
Fixed merge problem (and removed unintended change to MapTool.iss.template)

**Comment by xdy** [comment]
Obviously, this PR fixes all current dependabot PR:s, so any open such should be closed if/when this is merged.

**Comment by JamzTheMan** [comment]
Noting here for future self: Updating log4j2 lib past 2.12.1 currently breaks logging after packaged as uberjar...

**Pull request merged**
