### PR TITLE
Convert all abaille forms to intellij gui editor

### LINKED ISSUE #3792: [Refactoring]: Change UI editor from abeille to intellij
### Expected Benefits

- easier to change and maintain UI
- intellij knows more I18N ressources so they won't show up as unused

### Forms to convert
- [x] addRessourcesDialog
- [x] adjustBoardControlPanel
- [x] adjustGridControlPanel
- [x] campaignExportDialog
- [x] campaignPropertiesDialog
- [x] colorPanel
- [x] connectionInfoDialog
- [x] connectToServerDialog
- [x] editLabelDialog
- [x] editLookupTablePanel
- [x] exportDialog
- [x] layerSelectionDialog
- [x] lookupTablePane
- [x] macroButtonDialog
- [x] mapPropertiesDialog
- [x] newTokenDialog
- [x] preferencesDialog
- [x] startServerDialog
- [x] #3785
- [x] tokenPropertiesManagementPanel
- [x] transferProgressDialog
- [x] updateRepoDialog (unused)

### PR DESCRIPTION
**Pull request by thelsing**
### Identify the Bug or Feature request
resolves #3792

### Description of the Change
I converted all forms in a little marathon. Having used it quite a lot, I can now say that I like the intellij UI editor.
I removed I18Panel and the recursive translation of component texts as they are all translated automatically in the 
code generated from the GUI editor. Only ComboBox item can't be translated this way. I change the two instances that depended on this to manual translation. All other ComboBox items were already translated this way.

I also moved restructured the packages for the UI because we now have a *View.frm and a *View.java for each dialog/panel. This way they are grouped together.

I also fixed two bugs with AdjustGridDialog and AdjustBoardDialog introduced by the Eventbus change.

### Possible Drawbacks
Layout could be weird in some cases. I may have overlooked some translation in a Combobox.

### Release Notes
- Changed the way UI is created to make UI changed easier.

- - -
This change is [Reviewable](https://reviewable.io/reviews/rptools/maptool/3799)

### CODE REVIEW

**Comment by Azhrei** [comment]
Is this something that should perhaps go into a separate branch with separate test builds?  I'm just thinking of how big a snafu it would be for a glitch to be part of a normal release...?

**Comment by thelsing** [comment]
Who will test it in a different branch? Nobody will. In the develop branch at least developers will test the stuff they need during development. In a separate branch even that won't happen. 
We could create an test release for 1.13 to give users the ability to test the dialogs.
Also what changed is mostly the UI not the code behind it.

IMO separate branches only make sense when we plan a release in the next few days and want to safely store the changes. But even than it's better to just leave the PR open. That way we know faster when merging breaks.

**Comment by thelsing** [comment]
Also #3792 lists all the dialogs. So we can check them one by one before doing a release.

**Comment by kwvanderlinde** [comment]
Just a small marathon, eh? :laughing: 

I'm excited for these changes. Unless someone beats me to it, I'll take a look at them tomorrow (it's quite late here).

> Is this something that should perhaps go into a separate branch with separate test builds? I'm just thinking of how big a snafu it would be for a glitch to be part of a normal release...?

I don't see that as necessary. We can test these changes before merging, after merging, and then even if a release has a critical issue we can always patch or revert as makes sense. Kind of part of the release cycle anyways tbh :sweat_smile:

**Review by Phergus — APPROVED** [review]
:lgtm:

> Reviewed 94 of 158 files at r1, 67 of 67 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/rptools/maptool/3799#-:-NKiyneP4pmJ4nBxloNe:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @thelsing)

**Pull request merged**
