### PR TITLE
Add propertyType option for getTokens(), improve getTokens()

### LINKED ISSUE #676: Add "PropertyType" option for getTokens
**Is your feature request related to a problem? Please describe.**

It would be useful to augment `getTokens` to return only tokens of a given property type as defined in Campaign Properties (ex:"Basic").

For example if I get set a property type of "Trap", I could have `getTokens` only return trap tokens.

Not only would it be helpful for getting the right list of tokens, but it could improve the speed of `getTokens` when it is possible to narrow down the property type of the desired tokens.

**Describe the solution you'd like**
An additional field to the `condition` parameter of `getTokens` called `propertyType`, which can be a JSON array of property types, or a single type as a string

### PR DESCRIPTION
**Pull request by Merudo**
- Add new option "propertyType" to conditions in getTokens()
- Value can be a single type as string, or an array of types
- Simplify getTokens() code by removing the second loop. Now include/exclude is a filter property ("match")
- Improve performance of getTokens() by trimming the list continuously instead of constantly filtering the list of all tokens
- Close #676

---
This change is [Reviewable](https://reviewable.io/reviews/rptools/maptool/677)

### CODE REVIEW

**Comment by Merudo** [comment]
I rebased and force pushed the project - now Travis is fine with it :)

The code is exactly the same as what was approved.

**Comment by Phergus** [comment]
Something is stuck now.  Isn't recognizing approval.

**Comment by Merudo** [comment]
Should I open another PR?

**Comment by JamzTheMan** [comment]
I saw a error popuo in reviewable, something about not able to connect to GitHub API 

I will merge this after CI is done. Admin privileges FTW.

**Pull request merged**
