### PR TITLE
Restful functions

### PR DESCRIPTION
**Pull request by JamzTheMan**
Fixes issue #280

 * Also includes some dir cleanup, moved eclipse related files to their own dir under build-resources and added google-java-format-eclipse plugin for ease of use.
 * Updated build.gradle compile to implementation to match new 5.0 standards
 * development environments no longer error/log to Sentry.io

---
This change is [Reviewable](https://reviewable.io/reviews/rptools/maptool/312)

### CODE REVIEW

**Comment by Azhrei** [comment]
Wow, I like how Reviewable did that.  They're all in one post, with code extracts and links to the file for viewing in a browser...  I just tapped the code, entered my comment, then kept reviewing.  When I was done, I clicked on Publish and it added the post.  (Oh, and I clicked on "1 review" and added "Acknowledge".  Normally, without any comments, I would've clicked again for LooksGoodToMe.)

**Comment by JamzTheMan** [comment]
___
*[src/main/java/net/rptools/maptool/client/AppUpdate.java, line 72 at r3](https://reviewable.io/reviews/rptools/maptool/312#-La38yFv6CZwQFvEDfhI:-La3HAfKDZU21zi1-bD7:bw1nmhj) ([raw file](https://github.com/rptools/maptool/blob/257c679f24cb1c174e6df45d6361e4f6907d0459/src/main/java/net/rptools/maptool/client/AppUpdate.java#L72)):*
<details><summary><i>Previously, Azhrei (Frank Edwards) wrote…</i></summary><blockquote>

Does this trigger if the user is offline?
</blockquote></details>

Yes but is captured in the IOException and silently logs error.  I just pulled my plug to test the lib. :)

**Comment by JamzTheMan** [comment]
___
*[src/main/java/net/rptools/maptool/client/functions/RESTfulFunctions.java, line 121 at r3](https://reviewable.io/reviews/rptools/maptool/312#-La3ADoG-GaEa00NmoVR:-La3Hc5r4szh5TOnCA8l:b-7nizu5) ([raw file](https://github.com/rptools/maptool/blob/257c679f24cb1c174e6df45d6361e4f6907d0459/src/main/java/net/rptools/maptool/client/functions/RESTfulFunctions.java#L121)):*
<details><summary><i>Previously, Azhrei (Frank Edwards) wrote…</i></summary><blockquote>

Shouldn't one more character be added to the hard-coded string so that a different string with additional alpha characters doesn't match?  And not thrilled that this particular URL gets special handling...  Beyond building a plugin system, this will have to do.
</blockquote></details>

Ya, it could have been it's own function but I had originally matched it to the sendURL function. I'm ok with ripping it out really if we want.  They now have a Master/Minion in BETA that accepts REST api calls to their server and they do the push of the audio requests via a client...

**Comment by JamzTheMan** [comment]
___
*[src/main/java/net/rptools/maptool/client/functions/RESTfulFunctions.java, line 197 at r3](https://reviewable.io/reviews/rptools/maptool/312#-La3B2fe2V5SchI_qENa:-La3IW4w5uGkhVCkdhFA:b-va3f3s) ([raw file](https://github.com/rptools/maptool/blob/257c679f24cb1c174e6df45d6361e4f6907d0459/src/main/java/net/rptools/maptool/client/functions/RESTfulFunctions.java#L197)):*
<details><summary><i>Previously, Azhrei (Frank Edwards) wrote…</i></summary><blockquote>

Why isn't parameter 3 handled the same as in the previous IF statement?
</blockquote></details>

because if you pass 5 parameters, i know the last one is suppose to be a boolean. Full Response is always the last parameter passed (if it is passed) So only if you pass 4 do I need to check if you sent me headers  or sent me a boolean.

**Comment by JamzTheMan** [comment]
___
*[src/main/java/net/rptools/maptool/client/functions/RESTfulFunctions.java, line 261 at r3](https://reviewable.io/reviews/rptools/maptool/312#-La3BV9mC5P2l_0sEJf_:-La3JMd8ECV1ki6XGpTg:bmc7l6m) ([raw file](https://github.com/rptools/maptool/blob/257c679f24cb1c174e6df45d6361e4f6907d0459/src/main/java/net/rptools/maptool/client/functions/RESTfulFunctions.java#L261)):*
<details><summary><i>Previously, Azhrei (Frank Edwards) wrote…</i></summary><blockquote>

This block of code is the same as the previous method.  Refactor?
</blockquote></details>

I'm setting both a boolean and a map based on params, i'll think upon it, not sure if it's going to reduce it by to many lines. It's really less than 10 lines of code total. Google format does make it look larger lol.

**Comment by JamzTheMan** [comment]
___
*[src/main/java/net/rptools/maptool/client/functions/RESTfulFunctions.java, line 271 at r3](https://reviewable.io/reviews/rptools/maptool/312#-La3BaCq9I4-jNfEE9pp:-La3KIwk8RiiHHmzqOxL:bbu3jlm) ([raw file](https://github.com/rptools/maptool/blob/257c679f24cb1c174e6df45d6361e4f6907d0459/src/main/java/net/rptools/maptool/client/functions/RESTfulFunctions.java#L271)):*
<details><summary><i>Previously, Azhrei (Frank Edwards) wrote…</i></summary><blockquote>

Ditto — same as previous method; refactor?
</blockquote></details>

ditto, how best to refactor...

**Comment by JamzTheMan** [comment]
___
*[src/main/java/net/rptools/maptool/client/functions/RESTfulFunctions.java, line 315 at r3](https://reviewable.io/reviews/rptools/maptool/312#-La3Bl4l4xGOThdgkC5P:-La3Kd-s-txayHSSTxZ2:b-ve3yvb) ([raw file](https://github.com/rptools/maptool/blob/257c679f24cb1c174e6df45d6361e4f6907d0459/src/main/java/net/rptools/maptool/client/functions/RESTfulFunctions.java#L315)):*
<details><summary><i>Previously, Azhrei (Frank Edwards) wrote…</i></summary><blockquote>

Oooo, new "try with resources".  Shiny! ;)
</blockquote></details>

:smile:

**Comment by Azhrei** [comment]
> _[src/main/java/net/rptools/maptool/client/functions/RESTfulFunctions.java, line 261 at r3](https://reviewable.io/reviews/rptools/maptool/312#-La3BV9mC5P2l_0sEJf_:-La3JMd8ECV1ki6XGpTg:bmc7l6m) ([raw file](https://github.com/rptools/maptool/blob/257c679f24cb1c174e6df45d6361e4f6907d0459/src/main/java/net/rptools/maptool/client/functions/RESTfulFunctions.java#L261)):_
> 
> Previously, Azhrei (Frank Edwards) wrote…
> I'm setting both a boolean and a map based on params, i'll think upon it, not sure if it's going to reduce it by to many lines. It's really less than 10 lines of code total. Google format does make it look larger lol.

Darn.  I always tell my students that, "Copy-and-paste isn't code reuse.  Copy-and-paste is 'bug propagation'." 🙂

**Comment by JamzTheMan** [comment]
So, I'm hitting the done button after each reply and I probably shouldn't? So mine are coming in one post each. aaak

**Comment by JamzTheMan** [comment]
I get it, you should have seen it before I refactored lol
I originally had the delete in with post/put/patch as well but I wasn't 100% sure. From what I could research, DELETE *can* have a body but it's (usually?) ignored. OkHTTP lets you do a delete() with or without a body. So I just decided to not allow the body. 
I guess DELETE looks a lot more like GET now, maybe I can refactor it into GET method...

**Comment by JamzTheMan** [comment]
committed to soon, belay that review...

**Comment by JamzTheMan** [comment]
ok, refactored so probably have to go over it from scratch, hopefully it's cleaner & easier to read this time...

**Pull request merged**
