### PR TITLE
Revert "Bump jts-core from 1.16.1 to 1.18.1"

### PR DESCRIPTION
**Pull request by Phergus**
Reverts RPTools/maptool#2589

---
This change is [Reviewable](https://reviewable.io/reviews/rptools/maptool/2759)

### CODE REVIEW

**Review by Phergus — COMMENTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/rptools/maptool/2759)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Phergus)

**Review by Phergus — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/rptools/maptool/2759#-:-Mc_9QYFEN_DtmLvJShV:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Phergus)

**Comment by Phergus** [comment]
A geometry.buffer() fix in JTS 1.8.1 appears to have broken pathfinding on complex maps.

**Review by cwisniew — APPROVED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/rptools/maptool/2759)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Phergus)

**Review by cwisniew — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/rptools/maptool/2759)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Phergus)

**Review by Phergus — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/rptools/maptool/2759#-:-Mcd0okkDzo-lD6fzMru:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Phergus)

**Pull request merged**
