### PR TITLE
Add more icons from Rod Takehara

### PR DESCRIPTION
**Pull request by thelsing**
### Identify the Bug or Feature request
related to  #4638

### Description of the Change

This PR add some more icons that Rod provided and updates flatlaf to 3.3. As flatlaf dropped the *Contrast* themes, I removed them from MT too.

### Possible Drawbacks

Users might use those themes.

### Release Notes

- added more icons to icon theme "Rod Takehara"

- - -
This change is [Reviewable](https://reviewable.io/reviews/RPTools/maptool/4639)

### CODE REVIEW

**Comment by cwisniew** [comment]
I specifically haven't upgraded to 3.3 of flatlaf because of the dropped themes. On my list of things to do (but low priority as flatlaf 3.3 doesn't seem to add to much for us) is check to see if those themes are still available from https://plugins.jetbrains.com/search?tags=Theme and include them (like @bubblobill  theme was included).

**Comment by thelsing** [comment]
I didn't find any of the "Contrast" variants in the jetbrains search. Only the normal variants. IMO if anyone really wants one of the removed themes back they can raise an issue. 
The 3.3 version of flatlaf claims to use less memory with svg icons because they use a different svg lib. But I have no problem with reverting the flatlaf version bump.

**Comment by bubblobill** [comment]
Contrast themes are more likely to be used by people that need them than most of the many themes we have.
Best to hunt down the themes and include them because they will ask to have them back.
Accessibility is one area we can nail the competition.

**Comment by FullBleed** [comment]
I use the Monokai Pro Contrast (Material) theme.

Wonder why the contrast themes were dropped...

**Comment by thelsing** [comment]
I pulled the *Contrast* themes from flatlaf and added them to MT.

**Comment by kwvanderlinde** [comment]
> I pulled the _Contrast_ themes from flatlaf and added them to MT.

Careful with the licensing here ...

**Comment by thelsing** [comment]
> > I pulled the _Contrast_ themes from flatlaf and added them to MT.
> 
> Careful with the licensing here ...

Flatlaf uses apache license, so I see no problem with using the code.

**Comment by kwvanderlinde** [comment]
> > > I pulled the _Contrast_ themes from flatlaf and added them to MT.
> > 
> > 
> > Careful with the licensing here ...
> 
> Flatlaf uses apache license, so I see no problem with using the code.

That's my understanding as well, but there are requirements on retaining the original copyright notices and other things: https://github.com/JFormDesigner/FlatLaf/blob/0291dd5416b6bbf8ea2f3d5e4f7a4f22d6368e36/LICENSE#L89-L128

**Comment by cwisniew** [comment]
@thelsing there is a directory doc/3rd-party-libs that is angood a place as any of you need to include a text file with license file and what it applies to

**Comment by thelsing** [comment]
It seems spotless changed the copyright headers, I'll change them back. We already have multiple files with the apache 2.0 license in doc/3rd-party-libs.

**Review by cwisniew — APPROVED** [review]

**Pull request merged**
