### PR TITLE
Add functions isOverlayRegistered, closeOverlay, getOverlayProperties

### PR DESCRIPTION
**Pull request by Merudo**
- Add overlay helper functions isOverlayRegistered, closeOverlay, getOverlayProperties
- Functions described in #1669

---
This change is [Reviewable](https://reviewable.io/reviews/rptools/maptool/1826)

### CODE REVIEW

**Comment by cwisniew** [comment]
In HTMLOverlayPanel

- Its probably better to use ConcurrentHashMap rather than Collections.synchronizedMap(), in fact we should probably replace synchronizedMap() where we can when we come across it (where we can being anywhere that is not serialized as that would break save compatibility).
- if the return of getOverlays() is not intended to be modified it should return a copy of / read only version of overlays. If it is its probably even more important its a ConcurrentHashMap.
- Can you also make the MapUtil inner class private too, it should probably be replaced using streams at some point but until then its best to make sure it doesn't find its way to being used elsewhere (it will be weird to see HTMLOverlayPanel.MapUtil.sortByValue() popping up in code base in areas that have nothing to do with overlays)

**Comment by Phergus** [comment]
@Merudo holding pending action on Craig's comments.

**Comment by Merudo** [comment]
Thank you for your comments, @cwisniew 

1) The reason I used a `Collections.synchronizedMap` instead of a `ConcurrentHashMap` is that overlays are kept in an ordering corresponding to the z order of the overlays. `ConcurrentHashMap` does not support such ordering, but `Collections.synchronizedMap` together with `LinkedHashMap` do.

2) Agreed.

3) Sure.

**Comment by Merudo** [comment]
Instead of a ConcurrentHashMap I could use a ConcurrentSkipListMap.

**Comment by cwisniew** [comment]
> Instead of a ConcurrentHashMap I could use a ConcurrentSkipListMap.
Yep if you want sorted then this is probably way to go.

**Comment by Merudo** [comment]
The added commit add these changes:

- Replace overlay collection LinkedHashMap with ConcurrentSkipListSet
- Change getOverlays to return a clone instead of the collection
- Remove MapUtil

**Comment by melek** [comment]
All three functions added to the wiki and can be seen here:
https://lmwcs.com/rptools/wiki/Category:Overlay_Function

I left all with the 'stub' template until they are reviewed/improved.

**Pull request merged**
