### PR TITLE
Add macro editor syntax highlighting for defined token properties.

### PR DESCRIPTION
**Pull request by selquest**
Adds syntax highlighting for token props.

Couple of reservations with this particular implementation:
1. not particularly efficient - a new instance of `MapToolScriptSyntax` is instantiated each time a macro editor dialog is opened, so it's not ideal to have to re-add all defined properties each time that happens.  It already does this with reserved words, special variables, etc. though so this isn't really a new problem.  Micro-optimization of this specific chunk isn't really worth the added complexity, especially without knowing what plans might exist for revised syntax highlighting approaches in MTScript2.
2. New properties _created_ during a given session will be properly highlighted the next time a macro editor dialog opens, but because the `macroFunctionTokenMap` is never cleared any properties that are _removed_ during a session will continue to be highlighted until the next restart.  A similar limitation already applies to highlighting of UDFs, so I don't see this as especially problematic.

I also toyed with the notion of restricting highlighted properties to those applicable to the actual type of the token holding the macro (for token macros), but the current code path doesn't provide that opportunity if we wanted to... and it would get complicated around things like Lib:macros anyway, so I abandoned that idea.

Fixes RPTools/maptool#2352

---
This change is [Reviewable](https://reviewable.io/reviews/rptools/maptool/2353)

### CODE REVIEW

**Review by cwisniew — APPROVED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/rptools/maptool/2353)* status: :shipit: complete! all files reviewed, all discussions resolved

**Comment by cwisniew** [comment]
Moving to 1.9.0 as next beta for 1.8 is due in next couple of days and we want to concentrate on getting out the door. (just fixing some bugs)

**Comment by selquest** [comment]
@Phergus any chance we can get this in 1.8.5?  I know that's still a "bugfix" release, but this is such a small change for being a pretty big QoL improvement... kind of a shame to keep putting it off.

**Review by Phergus — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/rptools/maptool/2353#-:-MYIiDP67sE3tpcUP-13:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @selquest)

**Pull request merged**
