### PR TITLE
Some progress towards a Swedish translation.

### PR DESCRIPTION
**Pull request by xdy**
I started this back in april and promptly forgot about it till now...
I've cleaned it up some, currently at something like 40% of a first pass through the file.
Mostly creating this PR to be able to work on it using Crowdin.

---
This change is [Reviewable](https://reviewable.io/reviews/rptools/maptool/967)

### CODE REVIEW

**Comment by xdy** [comment]
Closing this till travis works better. Also, I should have done a branch locally...

**Comment by Azhrei** [comment]
Hi @xdy.

I realize you want to build MapTool from source, but it's not required to test your Swedish translation.

You can insert your translation file into the JAR file directly, then assign the language you want to use on the command line.  (I don't recall the option off-hand; something like, `-Dlanguage=en_US` for US English, for example.)  Just be sure that you recreate the directory structure so that the translation file is adjacent to the others...

**Comment by Phergus** [comment]
The CrowdIn PRs seem to be working fine.  I added Swedish as a target language so you should be able to start from there.

**Comment by xdy** [comment]
@Azhrei Yeah, I didn't bring my usual commit discipline to this unfortunately, doing a PR for a feature from master wasn't a particularly bright idea. I blame myself from april rather than admit fault now for not thinking when I made the PR. :)
(I ended up doing three things at once, adding Swedish language, try to get a green PR by fixing Travis, trying to get it to build locally using openjdk (with javapackager backport)/openjfx 11. All three of which belong on separate branches...)

@Phergus Thanks!

**Pull request closed without merging**
