### PR TITLE
Renames option to "Render Pages", adds tooltip

### PR DESCRIPTION
**Pull request by xdy**
See #1518

---
This change is [Reviewable](https://reviewable.io/reviews/rptools/maptool/1601)

### CODE REVIEW

**Comment by Phergus** [comment]
@xdy   Did you check that setting when you did the PR?   This one is also not allowing updates by maintainers.  If you get the latest changes on your branch I'll be able to merge this before any other changes go through.

**Comment by xdy** [comment]
Strangely enough I do not have that setting available (I took a screenshot when I noticed that, just in case the same problem pops up)
image
Anyway, I'll update the branch again, and check if I have some strangely set default on my github account.

**Comment by xdy** [comment]
Couldn't find any suspicious settings.
I'll try creating a Draft Pull Request next time, see if that behaves differently.

**Comment by Phergus** [comment]
Well updating your PR allowed it to merge since it was current.  So that's done.

I don't normally use the Compare to do a PR.  After pushing up to my repo a prompt appears on GitHub to do a PR and I just follow that through.

**Pull request merged**
