### PR TITLE
Workaround for bug in i1742

### PR DESCRIPTION
**Pull request by mrkwnzl**
Solves a bug in #1742. Bug discussed in #1318.

---
This change is [Reviewable](https://reviewable.io/reviews/rptools/maptool/1747)

### CODE REVIEW

**Comment by mrkwnzl** [comment]
Sorry, must have done something wrong here.

**Comment by Phergus** [comment]
Did you make your fix branch off of master perhaps?

**Comment by mrkwnzl** [comment]
Yeah, seems like it. I’m trying to sort this out. Sorry for the confusion.

**Comment by Phergus** [comment]
No worries. I've done much, much worse.

**Pull request closed without merging**
