### PR TITLE
Limit the types of assets that can be dropped into MapTool

### LINKED ISSUE #2527: Filter out Assets that shouldn't be included when drag and dropped on to MapTool
**Describe the bug**
MapTool allows many file types to be dragged and dropped which are added to the campaign even if MapTool could never use them.

**To Reproduce**
Drag and drop a zip file or ebook on to MapTool and examine the campaign. It will be added to the map as the broken image (large red X) but the asset will be added to the campaign. 

**Expected behavior**
MapTool should not add the file and should inform users that the file can not be added.

**MapTool Info**
Version info: Probably all of them

**Additional context**
Since some people are using this to add audio/text to the campaign the fix should not stop this from occurring. Since this is not adding new functionality to support storing these types there is no requirement to change the red X to something else, that can be done as part of #2526

### PR DESCRIPTION
**Pull request by cwisniew**
Users who drag invalid file types on to MapTool will now be informed that the file can not be added (and MapTool will not add them).
Certain non image files will still be allowed, these are
* audio/*
* text/html
* text/markdown
* text/plain
* application/pdf
* text/javascript?
* text/css

Fixes #2527

---
This change is [Reviewable](https://reviewable.io/reviews/rptools/maptool/2528)

### CODE REVIEW

**Review by Phergus — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/rptools/maptool/2528#-:-MY0OV6c7hf0cqXtHdjc:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @cwisniew)

**Comment by Phergus** [comment]
Should we add `application/json` to the list?

**Comment by cwisniew** [comment]
> Should we add `application/json` to the list?

Yeah I missed that one, added to PR

**Review by Phergus — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/rptools/maptool/2528#-:-MY3HtdC1Vdbp3pZVJLQ:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @cwisniew)

**Pull request merged**
