### PR TITLE
synchronize selected layers between tool and add hotkeys

### LINKED ISSUE #1998: Hotkeys for Layer Selection
**Is your feature request related to a problem? Please describe.**
It is distracting when I have to look away from what I'm currently working on to click on a button to swap my layer.

**Describe the solution you'd like**
I would like hotkeys for each of the layers including the VBL. This way I can focus on the map and not on clicking buttons.

**Describe alternatives you've considered**
A workable alternative would be a single hotkey which cycled through the layers. This is less desirable as I would have to repeat the same hotkey to get to a desired layer. And if I miss the layer I have to cycle around again.

### LINKED ISSUE #3731: [Feature]: Consistent layer selection for interaction, drawing and template tools.
### Feature Request

Because different tools have their own memory of which layer is current, I have to make sure I am on the expected layer after I switch tools or else risk putting stuff on the wrong layer. I find this inefficient in terms of workflow and also mentally burdensome to remember.

### The Solution you'd like

All tools that use the layer selection box would agree about which layer is currently selected. Switching tools would not switch layers but would leave the last selected layer as current.

Also if there are any other things I'm not thinking of that have their own layer selection, they would also be brought in line with the tools.

### Alternatives that you've considered.

I haven't come up with anything.

### Additional Context

It's worth pointing out that template tools and (most) drawing tools already share a layer selection. As far as I'm aware it's just the pointer interaction tool and the delete drawing tool that have their own selections.

As a concrete example, let's say I change to the background layer and drag a token onto it;
image

Then I want to also draw a box on the background layer. So I change to the rectangle drawing tool and get surprised about being back on the token layer:
image

### PR DESCRIPTION
**Pull request by thelsing**
### Identify the Bug or Feature request
fixes #3731
fixes #1998

### Description of the Change

Moved the LayerSelectionDialog to DefaultTool. Tools are still responsible for displaying it.
The dialog now always sets the active layer in ZoneRenderer. Tool that need to notified of a layer change can overide the selectedLayerChanged method.
(Commented out because if discussion.) I also added CTRL + 1-4 as hotkeys to select layers.

### Possible Drawbacks
Nothing.

### Documentation Notes
/* Layers can now be changed via CTRL - 1 - 4 */

### Release Notes
/* - added CTRL+1-4 hotkeys for layer selection */
- synchronize selected layer across different tools

- - -
This change is [Reviewable](https://reviewable.io/reviews/rptools/maptool/3776)

### CODE REVIEW

**Comment by kwvanderlinde** [comment]
Appreciate the synchronization change. Broadly looks good, though can't really look closely at the moment.

But I'm not convinced about the hotkeys, and there hasn't been any discussion on them. My reactions:
- Is there other software based on a layering paradigm that we could emulate? Thinking of whether there is already a defacto standard keybindings that we could leverage. Are these binding that?
- There is a [competing idea](https://github.com/RPTools/maptool/issues/3678#issuecomment-1257499458) for using CTRL+number for token grouping/selection. Very common in RTS, might be valuable in MT as well, but would be incompatible with these layer hotkeys.
- How do these hotkeys age if there is a change to layers? E.g., by adding additional layers, either built-in or custom?

**Comment by Azhrei** [comment]
I believe the Cmd+[1-4] shortcuts should be fine on macOS.  (I've checked the docs and I see that Shift+Cmd+[1-5] are used.)

In regards to future layer expansions, I would expect that Meta+1 moves to the Background layer, and if there are multiple, then repeated Meta+1 keystrokes would cycle through them.  If/when additional layers are added, the keystrokes would/could change, and that could be _very_ confusing!  I picture a new "Foliage" layer that is between the GM/Hidden layer and the Object layer, for example.  (Yeah, silly layer.  But that's not the point. ;) )

I would like to see the hockey changes separated from the other functionality of this patch.  That allows for more discussion while getting the basic refactoring ready and in-place.

**Comment by thelsing** [comment]
> Can we get a function to change layers, too?
There is #3708 for this. I'm not changing any macro stuff for now.

I think users really should be able to to change hotkeys. This is part of #3767

I'll disable the hotkeys for now.

**Review by kwvanderlinde — APPROVED** [review]

**Comment by Azhrei** [comment]
I saw this was merged.  We'll need the wiki updated, probably with a note that it applies to v1.13+.  Thanks @thelsing for this. :)

**Comment by aliasmask** [comment]
Will players still be able to bind macros with those hot keys, or have they been removed from the possible choices?

**Pull request merged**
