### PR TITLE
Fix #313 add macro.catchAbort and macro.catchAssert to syntax

### LINKED ISSUE #313: Macro Editor Help needs update for macro.catchAbort & macro.catchAssert
As it says.  The editor isn't recognizing `macro.catchAbort` & `macro.catchAssert`.

### PR DESCRIPTION
**Pull request by oliver-szymanski**
This change is [Reviewable](https://reviewable.io/reviews/rptools/maptool/320)

### CODE REVIEW

**Comment by Azhrei** [comment]
I would much rather this be done dynamically.  Is there a method call that the code could make that lists all of the variables at runtime instead of hard-coding them?

**Comment by oliver-szymanski** [comment]
Currently the static way is implemented for all special chars,  so I just added them. I like a dynamic approach more anyway, so I will change that (at least for these new special vars)

**Comment by oliver-szymanski** [comment]
Done. Functions can now define specials variables that are picked up in syntax highlighting and auto completion.

Also fixed a Maptool issue, that existing special vars and reserved keywords showed up in syntax highlighting but not in auto completion. Not sure if there was ever a Jira for this latter bug.

**Comment by JamzTheMan** [comment]
Fixes #313

**Pull request merged**
