### PR TITLE
fix for FoW issue

### PR DESCRIPTION
**Pull request by ebudai**
Restores previous handling of VoFoW tokens to address #2151

---
This change is [Reviewable](https://reviewable.io/reviews/rptools/maptool/2153)

### CODE REVIEW

**Comment by nmeier** [comment]
this looks like a simple revert rather than a fix that carries the intended change forward, is that so?

**Comment by nmeier** [comment]
The whole code block you're intending to revert was removed on purpose to improve readability. I suggest to extend the test case and handle object layer objects correctly rather than going half a step back as you're bringing back the multi page if-else statement.

**Comment by ebudai** [comment]
You are correct, it's a reversion instead of a "fix".  I attempted to reduce it, but the condition on the else block looked strange, so I just put it back to what it was when it was working.  I'll reattempt.

**Comment by ebudai** [comment]
I have reduced it as much as I can.  I cannot seem to find any tests regarding zone rendering to extend.

**Comment by ebudai** [comment]
I am having trouble reproducing the issue on the develop branch with the test campaign included in your (now deleted) comment, but that is almost certainly my fault.  I'll continue to investigate after work.

**Comment by ebudai** [comment]
Apologies, the comment wasn't deleted; I confused the discussion in the PR with the discussion here.

I cannot get the block to reduce further.

**Comment by Phergus** [comment]
@nmeier  did you have other thoughts on this?

**Comment by ebudai** [comment]
@nmeier stated he would attempt to rectify #2151 via the original refactoring.  I have nothing more to contribute.

**Pull request merged**
