### PR TITLE
FogUtil.calculateVisibility() speed improvements

### PR DESCRIPTION
**Pull request by ebudai**
… improved

---
This change is [Reviewable](https://reviewable.io/reviews/rptools/maptool/2150)

### CODE REVIEW

**Comment by Phergus** [comment]
What was the performance improvement from your testing?

**Comment by ebudai** [comment]
https://docs.google.com/spreadsheets/d/1rs7saqvNUSViIN1Zk_s71Cg72SZT-hnA-C8W0oGtLiE/edit?usp=sharing

**Comment by cwisniew** [comment]
> What was the performance improvement from your testing?

It would be interesting to know this as well... 

I have approved it in any case though as its a fairly standard optimisation (comparing squares of distances/magnitudes rather than tanking square root and comparing) when it comes to computer graphics with no down sides and it makes even more sense in this case where the original value had to be multiplied by 1000 so that the sort was stable.

**Comment by Phergus** [comment]
Even 10% improvement will be nice.

**Pull request merged**
