### PR TITLE
Bug Fixes for 1801 and 1804

### PR DESCRIPTION
**Pull request by nmeier**
Token image handling is slow, doesn't break rendering of combination halo/state/facing now #1801
Rework zone (map) selection that doesn't break scrolling #1804

---
This change is [Reviewable](https://reviewable.io/reviews/rptools/maptool/1810)

### CODE REVIEW

**Comment by nmeier** [comment]
Added on tiny change to revert back popup menu's preferred size - so there's no scrollbar space reserved after it goes way when number of map goes back to <=20

**Comment by JamzTheMan** [comment]
Shouldn't it be based on screen size and not number of maps? What screen scaling and resolution only allow 15 maps?

**Comment by nmeier** [comment]
@JamzTheMan 20 was the old limit, you're right though, one could argue that something like half the screen should be used for that popup,

**Comment by JamzTheMan** [comment]
Gotcha.

**Comment by Phergus** [comment]
Wouldn't want more than that.  Too much scrolling when the mouse-wheel is faster.

**Pull request merged**
