### PR TITLE
Correctness issues

### PR DESCRIPTION
**Pull request by ebudai**
This change is [Reviewable](https://reviewable.io/reviews/rptools/maptool/2148)

### CODE REVIEW

**Comment by Phergus** [comment]
___
*[src/main/java/net/rptools/maptool/client/ui/Scale.java, line 29 at r1](https://reviewable.io/reviews/rptools/maptool/2148#-MDr4OOmE0VmErwbUpe3:-MDrF1YzCmOHQlVb4UgG:b-hkdwwq) ([raw file](https://github.com/rptools/maptool/blob/9bcac63f0fb3d6697de60398e9f5fab5dd1cec51/src/main/java/net/rptools/maptool/client/ui/Scale.java#L29)):*
<details><summary><i>Previously, ebudai (Eric Budai) wrote…</i></summary><blockquote>

Do you do this, or should I submit some tests?
</blockquote></details>

It's expected that prior to submitting a PR that you run MT off your code and load a campaign, exercise various macro functions, move tokens, expose FOW, save campaign and then try to load it in the current release version, same for exporting/importing maps and just generally make sure nothing has broken.

**Comment by Phergus** [comment]
@ebudai  Eric, these changes broke the Export Screenshot.  Can you look at it?

**Comment by ebudai** [comment]
It's good timing; I have the next two days off.  Stellaris can wait...

**Comment by ebudai** [comment]
Had to submit a new PR as it seems I deleted the correctness_issues branch

**Comment by Phergus** [comment]
@ebudai  comment on #2287 please so that I can assign it to you

**Pull request merged**
