### PR TITLE
Added default username to preferences

### PR DESCRIPTION
**Pull request by Phergus**
For issue #2546: Under Application tab -  Client is a Default Username field for the username that appears in the MT title bar when a personal server is running.  The default is "Anonymous User" and no longer uses the operating system username.

image

image

---
This change is [Reviewable](https://reviewable.io/reviews/rptools/maptool/2650)

### CODE REVIEW

**Comment by Irarara** [comment]
Shouldn't the default name be localized?

**Comment by Phergus** [comment]
Oops.  Good catch!

**Review by cwisniew — COMMENTED** [review]
> Reviewed 2 of 5 files at r1, 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/rptools/maptool/2650)* status: 4 of 5 files reviewed, all discussions resolved (waiting on @Azhrei)

**Review by cwisniew — APPROVED** [review]
> Reviewed 1 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/rptools/maptool/2650)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Azhrei)

**Pull request merged**
