### PR TITLE
Startup lock token edit 2001

### LINKED ISSUE #1104: Option to not allow players to access and use their Library window to drop things onto the map.
**Is your feature request related to a problem? Please describe.**
Players can drag and drop their own tokens onto the map from their own Library window during a game.  As a GM, I would like to have an option to disallow players access to their Library window -- or at least not be able to drag and drop their own tokens onto the map.

I've had some players thoughtlessly drop random tokens onto the map, and that damages the gaming experience for everyone else.

**Describe the solution you'd like**
When starting the server, one of the options presented is a checkbox to allow the GM to **disable** player ability to -- or as an option we set in Preferences:

1. access their own Library window

2. drag and drop tokens onto the map

**Describe alternatives you've considered**
I don't know of an alternative other than to ask players not to do it when they do -- and they so far comply (but it's still slightly awkward for everybody).  It would be better to just disable access.

**Additional context**

### LINKED ISSUE #2001: Add option to have "Lock Player Token Editor" checked as the startup default.
**Is your feature request related to a problem? Please describe.**
I always want to have "Lock Player Token Editor" (found under the "Tools" menu) checked -- and I keep forgetting to check it.

**Describe the solution you'd like**
I would like to have MapTool startup with "Lock Player Token Editor" checked as the default.  I suggest adding an option to Preferences on the Application tab to enable GMs to set a default.

**Describe alternatives you've considered**
I keep trying to remember to set that to checked each time I start MapTool to run a game, but I keep forgetting to do it.

**Additional context**
The "Lock Player Token Editor" feature is critical because it prevents players from editing their tokens, which can create concurrency problems if the GM is trying to modify the token through his Token Editor or via macros.

### PR DESCRIPTION
**Pull request by michaelperino**
### Identify the Bug or Feature request
Resolves #2001 Resolves #1104

### Description of the Change

-Option to lock player movement and token editing on launch of server that persists through stop and start of server.
-Option to block players from dropping tokens onto map. Also blanks out library window but leaves it there in case players have a custom window arrangement they like.

### Possible Drawbacks

The start server dialog is now longer than it was last month with more options GMs must read.

### Documentation Notes

Implemented change to getInfo("server") to track blocking of player asset insertion to https://wiki.rptools.info/index.php?title=getInfo. Here's what a blanked out library pane looks like. 
image

### Release Notes

- Implemented options for GM to control player token insertion, movement, and token editing on server startup.

---
This change is [Reviewable](https://reviewable.io/reviews/rptools/maptool/3179)

### CODE REVIEW

**Comment by Phergus** [comment]
___
*[src/main/java/net/rptools/maptool/client/AppActions.java, line 2222 at r1](https://reviewable.io/reviews/rptools/maptool/3179#-MoYoJs23dqZB23ZnV_M:-MoYoJs23dqZB23ZnV_N:b-oidqc2) ([raw file](https://github.com/rptools/maptool/blob/3a851144a35c6476ea0c72fbd12b97bf6a564699/src/main/java/net/rptools/maptool/client/AppActions.java#L2222)):*
> ```Java
>                 policy.setIsTokenEditorLocked(MapTool.getServerPolicy().isTokenEditorLocked());
>                 policy.setHiddenMapSelectUI(serverProps.getMapSelectUIHidden());
>                 policy.setIsMovementLocked(serverProps.getPlayerLibraryLock());
> ```

You are setting setIsMovementLocked() 3 different times based on 3 different server props.  This doesn't seem right.  Also why use if() blocks for just the following settings?

**Comment by Phergus** [comment]
@michaelperino see comments above.

**Comment by michaelperino** [comment]
Excellent points! Modified to delete redundant entries and conform to normal format!

**Review by Phergus — APPROVED** [review]
:lgtm:

> Reviewed 10 of 12 files at r1, 1 of 1 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/rptools/maptool/3179#-:-MoafKg22IR1Pdc7-qdt:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @michaelperino)

**Pull request merged**
