### PR TITLE
Fix minor bugs in setSnapToGrid() and getPropertyDefault()

### PR DESCRIPTION
**Pull request by Merudo**
- Fix null exception error if getPropertyDefault() is used with one parameter and there is no current token.  Issue #569 
- Fix setTokenSnapToGrid() returning true/false instead of 1/0

---
This change is [Reviewable](https://reviewable.io/reviews/rptools/maptool/572)

### CODE REVIEW

**Comment by Phergus** [comment]
@Azhrei , @JamzTheMan , @aliasmask , @Jaggeroth 
Any problems with changing the return value of setTokenSnapToGrid() from "true"|"false" to 1|0?

Need to tie the change to an issue.

**Comment by JamzTheMan** [comment]
Other than break existing campaigns I'm ok with it. It should be minor, probably not a lot of checks for the return value of a set function I would think.

**Comment by aliasmask** [comment]
Not sure if I even had the need to use that function. I doubt there will be much if any impact.

**Comment by Phergus** [comment]
Yeah.  Pretty sure I've never had reason to use it and I expect the impact will be minimal if noticed at all.

**Comment by Merudo** [comment]
I just realized setTokenSnapToGrid() doesn't actually return anything in 1.5.3, the true/false return is actually something I added in one of my commits.

**Comment by Phergus** [comment]
Then it definitely won't have any impact.  :)

**Pull request merged**
