### PR TITLE
Changed behaviour of adding token property. Added JSON export

### LINKED ISSUE #4768: [Feature]: Classic Token Properties menu within Campaign Properties OR advanced "Add" feature.
### Describe the Problem

Within the new Campaign Properties window, the Token Properties tab now has this neatly ordered and fancy looking menu. While this is arguably way more user friendly than the old text block, it also brings with it some major problems for me.

My first problem: I often need to copy the whole text block of various token properties to be able to edit them in my development documentation, where I can add notes or brainstorm for new features. With the new simplified Token Property menu, I can no longer copy multiple entries.

My second problem: In my campaign I regularly add new properties and remove old ones. This is still possible with the new menu but when adding new properties, I need to click "Move Up" a lot to put the property in the right place which is a quite tedious and time costly task.

I'm in no way against the new menu, as it is way more user friendly and easy to understand. So I'd be happy with some additions instead of a revert.

### The Solution you'd like

For the first problem, add an "export Token Properties" button, where you can export the token properties into a txt file or to the clipboard.
For the second problem, expand the "Add" button, so it adds the new entry above the currently selected property, instead of the bottom.

### Alternatives that you've considered.

Add a text edit option, where you can display the old text block. This would solve both problems with minimal effort.

### Additional Context

The reason I often copy token properties into an external documentation is because it's rather impractical to manipulate and document them within maptool. This could potentially also be handled by a way to comment on various properties. However I don't think that many people would use such a feature and it would probably make things more confusing for the regular user, so I'd prefer my solution suggestions.

### PR DESCRIPTION
**Pull request by bubblobill**
### Identify the Bug or Feature request
resolves #4768

### Description of the Change
When there is a table row selected and adding a new property, the new property is inserted at the selected row
Exporting campaign properties now allows exporting as JSON
Added message on JSON export advising they cannot be imported.

### Possible Drawbacks
none

### Documentation Notes
Changed addTokenProperty behaviour to insert at selected row (where appropriate) instead of appending to the list.
Exporting campaign properties now allows exporting as JSON
Added message on JSON export advising they cannot be imported.

### Release Notes
Adding a token property in campaign properties now adds the property at the selected row.
Exporting campaign properties now allows exporting as JSON.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RPTools/maptool/4972)

### CODE REVIEW

**Comment by bubblobill** [comment]
#4649

**Comment by cwisniew** [comment]
@bubblobill maybe I am a bit daft, but whats the reasoning behind being able to export as JSON file if it can not be imported at a later time?

**Comment by fishface60** [comment]
> @bubblobill maybe I am a bit daft, but whats the reasoning behind being able to export as JSON file if it can not be imported at a later time?

I could use it in generating documentation for my add-on by exporting to a file and having my documentation include it and parse it to generate a table.

I'll probably be parsing the content.xml of the unzipped .mtprops file instead though since I version control the properties of my add-on that way.

**Comment by bubblobill** [comment]
> @bubblobill maybe I am a bit daft, but whats the reasoning behind being able to export as JSON file if it can not be imported at a later time?

JSON is considerably more human readable than xml. I've seen numerous requests where people want to see what's inside. For folk that want to get to grips with what's inside the box it's a friendlier place than exporting/unzipping/parsing xml/ then writing your own and reversing the process.

**Comment by cwisniew** [comment]
> > @bubblobill maybe I am a bit daft, but whats the reasoning behind being able to export as JSON file if it can not be imported at a later time?
> 
> JSON is considerably more human readable than xml. I've seen numerous requests where people want to see what's inside. For folk that want to get to grips with what's inside the box it's a friendlier place than exporting/unzipping/parsing xml/ then writing your own and reversing the process.

yeah but all of these requests are so they can edit it :)

**Comment by bubblobill** [comment]
It's a very non-obvious feature. You have to export the campaign and choose ".json" or ".txt" in the file filter dropdown to get it.
Choices:
1. Leave it.
2. Leave it and don't tell anybody it's there (undocumented feature)
3. Leave it but remove the file filters so you have to explicitly name a ".json" target file (undocumented feature).
4. Leave it and put a JSON import feature on the TODO list (tell me I'm not hilarious)
5. Leave it, put a JSON import feature on the TODO list, and declare a new ".universal_campaign_one_size_fits_all_VTT_format" to the world so they have to adopt our format.
6. Remove it

**Review by cwisniew — APPROVED** [review]

**Review by cwisniew — APPROVED** [review]

**Pull request merged**
