### PR TITLE
Max window

### PR DESCRIPTION
**Pull request by oliver-szymanski**
This change is [Reviewable](https://reviewable.io/reviews/rptools/maptool/354)

### CODE REVIEW

**Comment by oliver-szymanski** [comment]
No idea how to fix this:
 > Could not GET 'https://jcenter.bintray.com/org/ajoberstar/grgit/grgit-core/3.0.0/grgit-core-3.0.0.pom'. Received status code 502 from server: Bad Gateway

**Comment by oliver-szymanski** [comment]
That URL is accessible via browser, so maybe the CI setup needs attention? Can someone advise please?

**Comment by cwisniew** [comment]
Seems to have been a hiccup where neither CI could get it, problems with bintray? In any case I have re-triggered all builds and the original issue (spotless format violation) is solved.

**Comment by JamzTheMan** [comment]
@craig has a magic finger... When the CI blows up I just have craig press the button for me, always does the trick ;)

**Pull request merged**
