### PR TITLE
Feature logging

### PR DESCRIPTION
**Pull request by JamzTheMan**
This change is [Reviewable](https://reviewable.io/reviews/rptools/maptool/433)

### CODE REVIEW

**Comment by JamzTheMan** [comment]
Closes #355 and maybe Close #118

**Comment by JamzTheMan** [comment]
Closes #335 and maybe Close #118

**Comment by cwisniew** [comment]
@JamzTheMan can you update so that the RPTools copyright is not appended on the source file from elsewhere. 

Thanks

**Comment by JamzTheMan** [comment]
Yep, just haven't had a chance yet. Will try and do it tomorrow.

**Comment by JamzTheMan** [comment]
@cwisniew JTextAreaAppender ignore added.

**Pull request merged**
