### PR TITLE
Remove unused dependencies found by gradlelint

### PR DESCRIPTION
**Pull request by Merudo**
- Remove 11 unused dependencies found by gradlelint
- Change to runtimeOnly: jide-shortcut, maptool.resource, commons-logging, commons-beanutils, slf4j-simple, jxpath, commons-jxpath, ezmorph, jai-imageio-core, imageio-core, imageio-jpeg, imageio-psd, xpp3_min, xmlpull, and bcmail-jdk15on
- #1056 for a general discussion of dependencies removal

---
This change is [Reviewable](https://reviewable.io/reviews/rptools/maptool/1195)

### CODE REVIEW

**Comment by JamzTheMan** [comment]
Umm, expect things to break after this merge, not sure I'm trusting that plugin, I see more than one lib that should be needed...

**Comment by Merudo** [comment]
If the code refers to a dependency only via reflection, gradlelint will mistakenly see it as unused.

I suggest we move such dependencies to `runtimeOnly` and document the reflection used.

**Comment by Phergus** [comment]
Did you try a `gradlew deploy` or `gradlew uberJar` after this change?

**Comment by Merudo** [comment]
> Did you try a `gradlew deploy` or `gradlew uberJar` after this change?

I did and there is no issue, but missing dependencies only needed at runtime via reflection could still cause `NoClassDefFoundError` errors.

**Comment by Phergus** [comment]
Okay, so I really meant did you then go on to test that the installer build and uberJar both worked?

**Comment by Merudo** [comment]
As far as I can tell, they work. But I probably didn't try every feature of MapTool.

For example, `org.bouncycastle:bcmail-jdk15on` is said to be used to "decrypt passworded/secured pdfs". Can MapTool even do that?

**Comment by Phergus** [comment]
Well MT can extract images from PDFs that have password protection but all the PDFs I've checked here had Copy Content allowed even with the password protection.  So I'm not sure when it might be needed.  @JamzTheMan ?

**Comment by Merudo** [comment]
Closed because of the likelihood of breaking an obscure feature outweighs the benefits of removing the dependency.

**Comment by JamzTheMan** [comment]
FWIW MT can not opened password locked PDF's at this time but it was required by PDFBox to open some "secured" PDF's (ones just signed)

Also the without the various imagei libs MT wouldn't always extract every image, so it may seem to work but you need to compare images extracted.

**Comment by Merudo** [comment]
Yep, the image libs are loaded at runtime by ImageIO, which is why the PR had it changed from `implementation` to `runtimeOnly`.

**Comment by JamzTheMan** [comment]
Ya, I have no problem changing them from implementation to runtimeonly. We can take that up in a separate PR.

**Pull request closed without merging**
