### PR TITLE
Fix #265 maximized window on startup

### LINKED ISSUE #265: Fix Window Size Memory
When you close maptool it remembers the last window size it had, which is great, except when it's maximized while being closed. If it's maximized while being closed it records the full monitor resolution as its size and the next time you launch it, it's not maximized but it is the same size as the monitor. That means parts of it hang off the screen. It's honestly just annoying and can be easily worked around, but it'd be nice to see it only record non-maximized window sizes, and also to remember if it was maximized last time and launch maximized.

### PR DESCRIPTION
**Pull request by oliver-szymanski**
This change is [Reviewable](https://reviewable.io/reviews/rptools/maptool/308)

### CODE REVIEW

**Comment by JamzTheMan** [comment]
We're cleaning up our Repo to follow GitFlow. I've targeted this against our Develop branch now.

**Comment by cwisniew** [comment]
This PR fails CI build, please fix.

**Comment by oliver-szymanski** [comment]
Not sure what happened here, originally this was just one change in one java file. Failing in CI with


FAILURE: Build failed with an exception.


* What went wrong:

A problem occurred configuring root project 'MapTool'.

> Could not resolve all artifacts for configuration ':classpath'.

   > Could not resolve org.ajoberstar.grgit:grgit-core:3.0.0.

     Required by:

         project : > org.ajoberstar.grgit:org.ajoberstar.grgit.gradle.plugin:3.0.0 > org.ajoberstar.grgit:grgit-gradle:3.0.0

      > Could not resolve org.ajoberstar.grgit:grgit-core:3.0.0.

         > Could not get resource 'https://plugins.gradle.org/m2/org/ajoberstar/grgit/grgit-core/3.0.0/grgit-core-3.0.0.pom'.

            > Could not GET 'https://jcenter.bintray.com/org/ajoberstar/grgit/grgit-core/3.0.0/grgit-core-3.0.0.pom'. Received status code 502 from server: Bad Gateway



No idea why as I worked before it was switched to develop branch.

I tried to rebase now and now the diff is showing so much more changes (that are not mine). I better start a new PR and use a clean branch

**Comment by oliver-szymanski** [comment]
Moved over to a fresh PR from develop branch. Same prob:
https://github.com/RPTools/maptool/pull/354

**Comment by oliver-szymanski** [comment]
All ok now in https://github.com/RPTools/maptool/pull/354

**Comment by JamzTheMan** [comment]
Looked like it had merge commits causing all that mess. Thanks for recreating, sometimes it's the easiest :)

**Pull request closed without merging**
