### PR TITLE
Removing warnings from java-doc

### PR DESCRIPTION
**Pull request by balp**
These commits should remove all the warnings from java-doc and make it possible to close (Issue #1223)

---
This change is [Reviewable](https://reviewable.io/reviews/rptools/maptool/1846)

### CODE REVIEW

**Comment by Phergus** [comment]
Thanks for the PR!  You'll need to run `gradlew spotlessApply` against the code and then commit/push any changes from that up.  That will fix the CI failures.

Also, as a general rule, comment on the issue itself to let us know you are working on something.

**Comment by balp** [comment]
I just started to play around in the code. I sure comment when I get into looking at other issues. I forgot the spotless on my later changes, noted as soon the CI build failed. I'm more worried I misunderstood some of the stuff i documented. Even if most was understandable. Been years since I worked in java... and even longer since java as a user application.

**Comment by balp** [comment]
BTW, Do you prefer squashed pull requests for full branches?

**Comment by Phergus** [comment]
@balp No real preference on that.

In general we recommend that contributors work off a branch from develop that is just for the particular issue/pr they are working on.

**Pull request merged**
