### PR TITLE
Changed getInfo("server") macro to use ServerPolicy.toJSON directly

### PR DESCRIPTION
**Pull request by Phergus**
Updated getInfo("server") macro function to pull JSON object from ServerPolicy instead of having duplicated code.
Updated ServerPolicy.toJSON() to include isAutoRevealMovement and isUseIndividualFOW.

Finish #663

---
This change is [Reviewable](https://reviewable.io/reviews/rptools/maptool/738)

### CODE REVIEW

**Comment by JamzTheMan** [comment]
___
*[src/main/java/net/rptools/maptool/client/functions/getInfoFunction.java, line 244 at r1](https://reviewable.io/reviews/rptools/maptool/738#-LpQ_6xy4JwbY2P6cbb9:-LpQ_6xy4JwbY2P6cbbA:b-gn4rf8) ([raw file](https://github.com/rptools/maptool/blob/b6714c11b716c12578699b47ac78cac288c394d8/src/main/java/net/rptools/maptool/client/functions/getInfoFunction.java#L244)):*
> ```Java
>       sinfo.put(
>           "initiative owner permissions",
>           ip.isOwnerPermissions() ? BigDecimal.ONE : BigDecimal.ZERO);
> ```

Are we going to leave this out now? Does it need it's own getInfo()?  I don't think it belongs in ServerInfo but it "may" break some existing macros?

**Comment by Phergus** [comment]
That taking it out of the server info may break some existing macros is certainly a concern.   Seems kind of silly though to put it in its own info block by itself.   It appears to be the kind of setting that is set once and stays that way much like the other server settings.  Are there other initiative related settings that would justify having a new getInfo("initiative")?

**Comment by JamzTheMan** [comment]
I can't think of any off the top but does not mean there isn't.

Semver tells us this shouldn't be a 1.5.x change. Well really, new features should bump our minor version number each time, only small changes and bug fixes should be 3rd dot increments...

ANYhoo, I think we should keep it for now and mark it deprecated in the wiki for removal in 1.6? In the meantime we can look to see where it can live, maybe there are some other random settings that would be useful to have?

If you can't easily modify that returned JSON from ServerPolicy, maybe overload the method in ServerPolicy and pass it a string and value to add?

**Comment by Phergus** [comment]
FWIW, it's also in the info block for "campaign" as is "initiative movement locked".

It is trivial to remove it from the server policy JSON object as it isn't actually used anywhere, just reported as info in the Sentry context and to macro getInfo().  Nothing internal to MapTool is going to care if it goes away.

**Comment by JamzTheMan** [comment]
Oh well then, if it's already in campaign info then it's a bug here and let's remove it. :)

**Comment by Phergus** [comment]
Don't see the need for it in both places and since two initiative options are already in the `campaign` info, we can stick with that.

**Pull request merged**
