### PR TITLE
Allow optionally building with no '.git' dir

### LINKED ISSUE #2708: maptool should be able to compile without a .git directory
**Is your feature request related to a problem? Please describe.**

Currently, maptool's build system depends on access to `git` metadata. This has two problems:

1. The source code archive on release (i.e. https://github.com/RPTools/maptool/archive/refs/tags/1.8.5.zip) can't be compiled
     ```
     $ wget https://github.com/RPTools/maptool/archive/refs/tags/1.8.5.zip
     $ unzip 1.8.5.zip && cd maptool-1.8.5
     $ ./gradlew
     FAILURE: Build failed with an exception.

    * What went wrong:
    A problem occurred evaluating root project 'MapTool'.
    > No .git directory found!
    ```

2. Linux distro packagers, like those for gentoo, nix, etc, generally prefer to package applications from a source-code tarball that does not contain a `.git` directory.

The 2nd reason is the primary motivation for me.

**Describe the solution you'd like**

Having some way to build maptool without a .git directory would be nice. I'll suggest having user-setable properties for things derived from .git right now, like so:

```
./gradlew -PnoGit=true -PgitTag=1.8.5 -PgitRevision=12345678
```

**Describe alternatives you've considered**

Not doing anything is a valid resolution to this. We can just say the source archives aren't supported, and distro packagers can just patch the build system themselves, rather than have a patch for it upstream.

### PR DESCRIPTION
**Pull request by euank**
This is primarily motivated by [packaging maptool with nix](https://github.com/euank/nixek-overlay/blob/d1e2adc0b191b194fbbf382a48f1c9d238e63209/pkgs/games/maptool/default.nix#L6-L25). In nix, it's
encouraged to avoid leaving around the '.git' for git repositories
because it can lead to some subtle nondeterministic behavior (i.e. it
doesn't always hash to the same thing, even though you're checked out to
the same commit).

Further, this allows building the source archives that are on the
'releases' page, though it admittedly does take a rather clumsy
invocation of gradle.

Other linux distros likely have similar desires to be able to compile
the program from a source tarball.

Fixes #2708

---
This change is [Reviewable](https://reviewable.io/reviews/rptools/maptool/2704)

### CODE REVIEW

**Comment by Phergus** [comment]
PRs require an open issue to be accepted.

**Comment by euank** [comment]
I've filed https://github.com/RPTools/maptool/issues/2708 for the related issue / feature request here, and I'm happy to discuss there.

**Comment by Phergus** [comment]
Thanks!

**Review by cwisniew — APPROVED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/rptools/maptool/2704)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @euank)

**Review by Phergus — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/rptools/maptool/2704#-:-MbZ4iI1020E-9StoCuM:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @euank)

**Pull request merged**
