### PR TITLE
Making user language available to macros.

### LINKED ISSUE #3515: [Feature]: include UI language in e.g. getInfo("client")
### Feature Request

Library tokens and add-ons are rarely, if ever, localizable. This is understandable for a lot of reasons. Not least of which it is not possible to get the UI language currently in use by MapTool. 
It would help a lot towards localizations of macros and user functions, if it was possible to get the UI language. 

### The Solution you'd like

I would think the prettiest solution would be to expand the client information returned from `getInfo("client")` to include a property containing the ISO 639-1 code for the selected language. 
This should of course be propagated to the javascript interface as e.g. `MapTool.clientInfo.userLanguage()`.

### Alternatives that you've considered.

_No response_

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by Tdue21**
### Identify the Bug or Feature request
fixes #3515

### Description of the Change
A feeble attempt at hacking MapTool to present user language to macros and javascript.

The information is accessible through getInfo("client") in MTScript, and MapTool.clientInfo.getUserLanguage() in Graalvm javascript.

Changes where mades in four files: 
- I18.java - A new static function `getLocale()` returns the value of `BUNDLE.getLocale().getLanguage().
- MapTool.java - A new static function `getLocale()` returns the value of `I18N.getLocale()`.
- getInfoFunction.java - Added a property `userLanguage`to the output json with the value of `MapTool.getLocale()`.
- JSAPIClientInfo.java - A new method `userLanguage()` was added to the `MapTool.clientInfo` member. This returns the value of `MapTool.getLocale()`.

### Possible Drawbacks
I do not believe there are any. 

### Release Notes
Added macro support for getting user language in MTScript and GraalVM javascript.

---
This change is [Reviewable](https://reviewable.io/reviews/rptools/maptool/3516)

### CODE REVIEW

**Comment by Phergus** [comment]
> I18.java - A new static function getLocale() returns the value of `BUNDLE.getLocale().getLanguage().

@Tdue21 isn't that going to get the locale of the system which is not necessarily the locale the JVM was started with?

**Comment by Phergus** [comment]
@Tdue21  you need to run `gradlew spotlessApply` on your branch and re-push.

**Comment by Tdue21** [comment]
> @Tdue21 isn't that going to get the locale of the system which is not necessarily the locale the JVM was started with?

I am not sure. I was unable to find where user language was loaded, but BUNDLE *seemed* to know it. 
I am happy to experiment further, if you want me to. 

I am extremely rusty in Java, not worked seriously with since around version 2. So, there is a lot of stuff I have no idea about. 
I have realized though, that I was wrong to look for it in the code, as it is of course loaded by the JVM. 

I will look into it a bit further.

**Comment by Tdue21** [comment]
> @Tdue21 you need to run `gradlew spotlessApply` on your branch and re-push.

Will do.

**Comment by Tdue21** [comment]
@Phergus I found a better way actually. (Which I think is what BUNDLE does too), but I have tested it without any user configuration, with english and with german... All three rendered the expected result. So this seems to work as intended.

**Comment by Phergus** [comment]
Excellent!

**Comment by Phergus** [comment]
@Tdue21 looks like you have an extra commit in there to MacroButtonDialog

**Comment by Tdue21** [comment]
> @Tdue21 looks like you have an extra commit in there to MacroButtonDialog

Yeah, I have no idea where it comes from. I assumed it was that there from the gradlew spotlessApply command.

**Comment by Phergus** [comment]
Spotless fixes formatting and doesn't add new code. ;)

You'll need to remove it from your commit.

**Comment by Tdue21** [comment]
> Spotless fixes formatting and doesn't add new code. ;)
> 
> You'll need to remove it from your commit.

Uh, I am not sure how to do that?

**Comment by Tdue21** [comment]
> > Spotless fixes formatting and doesn't add new code. ;)
> > You'll need to remove it from your commit.
> 
> Uh, I am not sure how to do that?

Oh! I know what it is about, but yes, it should not have been in here. My bad :(

I don't how to remove it though? 
Do I just roll the local file back to before, and commit that?

**Comment by Tdue21** [comment]
> > > Spotless fixes formatting and doesn't add new code. ;)
> > > You'll need to remove it from your commit.
> > 
> > 
> > Uh, I am not sure how to do that?
> 
> Oh! I know what it is about, but yes, it should not have been in here. My bad :(
> 
> I don't how to remove it though? Do I just roll the local file back to before, and commit that?

Ha! Figured it out. Should be fixed now.

**Review by Phergus — APPROVED** [review]
:lgtm:

> Reviewed 4 of 5 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/rptools/maptool/3516#-:-N8tnIse8_mD9gO53FKo:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Tdue21)

**Comment by Tdue21** [comment]
Awesome! now what? It *looks* like I am supposed to do something, but what?
image

**Comment by Phergus** [comment]
It's done.  It says everything is done but still says waiting on you.  Don't know why.  As long as I get all green lights I'm happy.

**Comment by Tdue21** [comment]
Awesome! I am now officially a contributor... Only 11 lines maybe ... but still :D

**Comment by Phergus** [comment]
Yup.  Feel free to update the wiki page for `getInfo()` now.  ;)

**Pull request merged**
