### PR TITLE
Update FogOfWarFunctions.java

### LINKED ISSUE #505: FOW functions: add "mapname" as valid argument
**Is your feature request related to a problem? Please describe.**
The code in FogOfWarFunctions.java makes it clear that all FOW functions are intended to take "mapname" as an argument, but the feature is not available for some FOW functions because of a bug.

**Describe the solution you'd like**
Fix the bug and allow the argument "mapname" to work as intended.

**Additional context**

The bug can be fixed by replacing

```
private Set<GUID> getTokenSelectedSet(final ZoneRenderer zr) {
    Set<GUID> tokens = MapTool.getFrame().getCurrentZoneRenderer().getSelectedTokenSet();
    Set<GUID> ownedTokens = MapTool.getFrame().getCurrentZoneRenderer().getOwnedTokens(tokens);
    return ownedTokens;
 }
```
by

```
private Set<GUID> getTokenSelectedSet(final ZoneRenderer zr) {
    Set<GUID> tokens = zr.getSelectedTokenSet();
    Set<GUID> ownedTokens = zr.getOwnedTokens(tokens);
    return ownedTokens;
  }
```

in FogOfWarFunctions.java

### PR DESCRIPTION
**Pull request by Merudo**
Fixes #505 for exposeFOW(). Function now accepts "mapname" correctly.

---
This change is [Reviewable](https://reviewable.io/reviews/rptools/maptool/506)

### CODE REVIEW

**Comment by Merudo** [comment]
Thanks for the comment JamzTheMan. I hope there will be a Maptool 1.5.4 so that the merge doesn't wait until 2.0.

**Comment by Phergus** [comment]
@JamzTheMan  You want to add a 1.5.4 project so these can be assigned there?

I could create the project but I don't now what if any template was being used for the existing ones.

**Comment by JamzTheMan** [comment]
@Phergus Done. FYI: We are using the Automated Kanban with Reviews.

**Comment by Phergus** [comment]
@JamzTheMan   Roger that.  Thanks.

**Pull request merged**
