### PR TITLE
Obvious static analysis fixes

### PR DESCRIPTION
**Pull request by ebudai**
Work on #2135 

This change is [Reviewable](https://reviewable.io/reviews/rptools/maptool/2132)

### CODE REVIEW

**Comment by Phergus** [comment]
@ebudai   Hi!  Thanks for diving in to help the community.

Two things.  There must be an issue opened for the PR(s) and you'll need to run `gradlew spotlessApply` to fix the formatting of the code.

https://github.com/RPTools/maptool/blob/main/doc/Code_Style_and_Guidelines.md

**Comment by ebudai** [comment]
Apologies!  Would you like one issue per change, or all of them in one?

**Comment by Phergus** [comment]
No worries.  For general code clean up you can just just use one issue and just update with the actions taken.

If you've identified a specific bug or problem that is impacting users through the UI or macro functions, it's better to keep things to one issue and hopefully one PR.

**Comment by cwisniew** [comment]
> No worries. For general code clean up you can just just use one issue and just update with the actions taken.
> 
> If you've identified a specific bug or problem that is impacting users through the UI or macro functions, it's better to keep things to one issue and hopefully one PR.

As above... Looking through these changes I think they are fine for the one general clean up issue/PR...

Ugh I cant believe there are so many double checks for null in the code base... :(

**Comment by ebudai** [comment]
There were several more useless null checks (esp after newing).  Would you like me to remove those as well?

**Comment by Phergus** [comment]
If you're already doing other fixes in a file might as well clean those up as well.

**Comment by ebudai** [comment]
One more quick question: there are several places where redundant null checks occur, but it might be to aid in debugging.  An example:

  public LargeImage(BufferedImage image, File cacheDir) throws IOException {
    info = loadInfo();
    if (info == null) {
      info = new ImageInfo(image.getWidth(), image.getHeight());
    }
    this.cacheDir = new File(cacheDir.getAbsolutePath(), getId(image));
    this.cacheDir.mkdirs();
    chunkize(image);
  }

  private ImageInfo loadInfo() {
    return null;
  }

In this example, should "if (info == null)" be removed?

**Comment by Phergus** [comment]
I don't think the LargeImage class is used at all.

**Comment by ebudai** [comment]
It's just an example, that kind of thing is all over.

**Comment by Phergus** [comment]
So no point in making changes in it then.

**Comment by ebudai** [comment]
Ok, but what about all the others?  Ignore those too?  They are not all in LargeImage, btw.

**Comment by Phergus** [comment]
If the redundant checks are in active code, go ahead and make the changes.  Just no point in fixing code that isn't used and will likely be excised at some point.

**Comment by ebudai** [comment]
There are other types of things to be cleaned up, such as static method called from instance, deprecated method calls (ie: new Boolean(true) -> Boolean.TRUE), redundant throws Exception, etc.  Should they all be here, or in separate PRs?

**Comment by Phergus** [comment]
They can all be lumped together.

**Pull request merged**
