### PR TITLE
move map with ctrl + arrow keys

### PR DESCRIPTION
**Pull request by matejdro**
Feel free to comment if I should move this somewhere else. From what I see, all user interactions are happening in `Tool` classes, so I added movement there.

---
This change is [Reviewable](https://reviewable.io/reviews/rptools/maptool/2359)

### CODE REVIEW

**Comment by Phergus** [comment]
Thanks for contributing to MapTool.  All PRs must have a corresponding Issue opened - in this case a Feature Request - with sufficient description of the changes to be made and to document the changes for users.

**Comment by matejdro** [comment]
Thanks for the reminder, I've made the issue.

**Review by cwisniew — APPROVED** [review]
> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/rptools/maptool/2359)* status: :shipit: complete! all files reviewed, all discussions resolved

**Comment by cwisniew** [comment]
Moving to 1.9.0 as next beta for 1.8 is due in next couple of days and we want to concentrate on getting out the door. (just fixing some bugs)

**Pull request merged**
