### PR TITLE
Add optional parameter mapName to getName() and setName()

### LINKED ISSUE #547: Functions setName() and getName() to have mapName as optional parameter
**Is your feature request related to a problem? Please describe.**
It is a pain to change properties of tokens on other maps. Instead of having to change the map and possibly create flickering, it would be better to add the mapName as additional optional argument.

**Describe the solution you'd like**
I would like the following functions in TokenImage.java to take a mapName parameter so they could work on tokens in other maps:

getName()
setName()

### PR DESCRIPTION
**Pull request by Merudo**
Close #547

---
This change is [Reviewable](https://reviewable.io/reviews/rptools/maptool/548)

### CODE REVIEW

**Comment by Phergus** [comment]
Wiki documentation needs to be updated.

**Comment by Merudo** [comment]
I don't believe the commit was merged - is that intended? Maybe something went wrong with github?

**Comment by Phergus** [comment]
Doesn't appear to be.  No idea what happened.

**Comment by JamzTheMan** [comment]
Looks like it. @Phergus did you mean to merge this? I'll reopen for now.

**Comment by JamzTheMan** [comment]
K, I kicked off the update branch so when CI is done can merge if all is still good with PR.

**Comment by Phergus** [comment]
@JamzTheMan  Was supposed to have merged.  Will see what happens after the CI stuff runs.

**Pull request merged**
